### ISSUE TITLE
Follow the system theme

### ISSUE THREAD

**Issue by julianfairfax** [Darkempire78/OpenCalc#1]
I see F-Droid inclusion is planned and I'm excited. The app should also be able to follow the system theme. Imv the colours in the dark mode are too bright and not as pastel as those in light mode. But this is probably subjective.

**Comment by Darkempire78** [comment]
Fdroid accepted OpenCalc , but we have to wait some hours or days before Fdroid repos update.

**Comment by Darkempire78** [comment]
You can suggest new hex code to change the colors, maybe it will be more beautiful (I'm not a design expert 🤣)

**Comment by julianfairfax** [comment]
> You can suggest new hex code to change the colors, maybe it will be more beautiful (I'm not a design expert rofl)

What about #88bb91, #85b5d2, and #bf879d? An interpretation of the light colours for dark mode, from a fellow person who is not a design expert. F-Droid would have to update the app (even though they haven't built it yet) if there are changes btw.

Looks like this:
![1](https://user-images.githubusercontent.com/43753131/181285674-ef1d5ba5-6c0d-40dd-9019-67893565f90c.png)

**Comment by julianfairfax** [comment]
It also seems the theme selection doesn't persist through app closing and reopenings. And no Material You

**Comment by Darkempire78** [comment]
Follow system theme added in the [v1.1.0](https://github.com/Darkempire78/OpenCalc/releases/tag/1.1.0)

**Comment by Darkempire78** [comment]
You can open a new issue for Material You support if you want or an other thing ^^

**Comment by Darkempire78** [comment]
@julianfairfax For the colors, perhaps taht we should make a poll or something like that idk ?

**Comment by julianfairfax** [comment]
> @julianfairfax For the colors, perhaps that we should make a poll or something like that idk ?

Idk where we doing the poll? How many answers we want? What are the options? How much time we allocating?

**Comment by julianfairfax** [comment]
@Darkempire78 Perhaps #5fa36b, #6791aa, and #95556e would be better? More legible

![image 2](https://user-images.githubusercontent.com/43753131/181383596-ef03858a-ba9b-4c45-a6ac-290a51f29ecb.png)
 
Maybe the top background colour should also be changed to be more legible? Something like #383737?

![image 3](https://user-images.githubusercontent.com/43753131/181383959-f7e3bd60-7e07-4d88-8a68-a9091d6d4b35.png)

**Comment by Darkempire78** [comment]
It looks nice 🤔

**Comment by julianfairfax** [comment]
> It looks nice thinking

I see you have a Discord server. i don't use Discord but i suppose you could do a poll there if you want. I'm no designer either and this is your app. But in my humble opinion I think this colour change would be nice to see. Thanks for developing this app!

**Comment by Leif-W** [comment]
As far as the proposed pastels on dark mode, they are all too bright, washed out.  In dark mode, probably nothing should be brighter than #7f7f7f, considerably less.  I'm no design expert, but this is basic common sense.  Dark mode is often used in the dark, because bright colors hurt the eyes.
