### ISSUE TITLE
Light theme option doesn't save on restart

### ISSUE THREAD

**Issue by ivan-volnov** [Darkempire78/OpenCalc#10]
Subj. Please fix it)

**Comment by Darkempire78** [comment]
This is very weird because it works on my phone.
What is your phone and your android version ?

**Comment by ivan-volnov** [comment]
[ArrowOS](https://arrowos.net/) v12.1 VANILLA

**Comment by ivan-volnov** [comment]
It shows already Light theme in options on app start. But the theme is dark.

**Comment by ivan-volnov** [comment]
Installed from F-Droid

**Comment by Darkempire78** [comment]
What is your version of OpenCalc ?

**Comment by ivan-volnov** [comment]
Oh, yep. The version number is 1.0.0. Please update.

**Comment by Darkempire78** [comment]
it does not update automatically on Fdroid ?

**Comment by ivan-volnov** [comment]
It's the current last version now.

**Comment by Darkempire78** [comment]
Yes I know but doesn't Fdroid automatically get the latest version from the repo?  Does it mean that I have to manually ask to update or maybe I'm wrong, this is the first time I put an application on Fdroid

**Comment by Darkempire78** [comment]
Try the v1.2.2 to check if the problem is fixed @ivan-volnov

**Comment by ivan-volnov** [comment]
Updated to 1.2.0 from F-Droid. It works now.

I guess F-Droid has a time lag for updates.
