### ISSUE TITLE
Can't scroll up to see the history

### ISSUE THREAD

**Issue by Nekothegamer** [Darkempire78/OpenCalc#103]
I'm not able to scroll up in order to see my past operations, like most calculators (including google's closed source one :/ )

below there's a video for proof:

https://user-images.githubusercontent.com/112352776/203588375-c82795e7-7521-4f3a-a1f6-edfa48ebb5d4.mp4

**Comment by Darkempire78** [comment]
It should be fixed know, wait for the next pre-release `beta2-2.0.0`
