### ISSUE TITLE
Some values are not correct

### ISSUE THREAD

**Issue by bartlibert** [Darkempire78/OpenCalc#107]
Some values are not correctly calculated, for example:

- [x] cos(90) (or cos(pi/2) in radians) is a very small number, but not zero as expected
- [ ] sqrt(2) squared does not yield 2, but a number slightly larger than 2

**Comment by Darkempire78** [comment]
?

**Comment by bartlibert** [comment]
Sorry, I started writing an issue, but my phone did an oopsie an apparently posted it already

**Comment by Darkempire78** [comment]
you are right, there are problems of calculation with cos and sin, but I have no idea why

**Comment by Darkempire78** [comment]
Calculations with trigonometry should show the right results now (1c136c7535671b3c945621673e85730ca5269bdd)

**Comment by Darkempire78** [comment]
I'm not sure than there is a way to fix the sqrt(2) squared tath does not yield 2

**Comment by Darkempire78** [comment]
My bad, it should be fixed now
