### ISSUE TITLE
Crash when tapping on history result

### ISSUE THREAD

**Issue by lefterisgar** [Darkempire78/OpenCalc#109]
Steps to reproduce:

1. Open OpenCalc
2. Scroll down to the history
3. Tap a value to copy it
4. Immediately, tap a different value

OpenCalc should crash.

[Here](https://stagbin.tk/lzkqqyh) is a log for further investigation.

Video:

https://user-images.githubusercontent.com/46350667/204142877-e0472f9b-a569-46d1-a83f-6b433d399057.mp4

**Comment by Darkempire78** [comment]
Can you check if the v2.0.0-beta3 fix the issue please ? @lefterisgar

**Comment by lefterisgar** [comment]
Takes a bit of effort, but yes, I can reproduce it on v2.0.0-beta3.

**Comment by Darkempire78** [comment]
What language is your phone in? @lefterisgar

**Comment by Darkempire78** [comment]
It must be fixed now, clear your history because there is impossible numbers like numbers with two decimal separator

**Comment by lefterisgar** [comment]
Awesome! Thank you!
