### ISSUE TITLE
crashes on "10(", "20(, "30(" etc.

### ISSUE THREAD

**Issue by pank** [Darkempire78/OpenCalc#111]
Hi

When I input something like `30(` opencalc crashes. `30x(` is ok. This is new behaviour in v2 beta2 from fdroid (i.e. it did not happen in the previous version, v1.8, I think).

I did not see a similar bug, but if I overlooked it my apologies.

**Comment by Darkempire78** [comment]
It is a duplicate of #106

**Comment by pank** [comment]
Looks like it. I missed that one. Sorry!
