### ISSUE TITLE
Adding a decimal point after two-digit numbers adds a 0

### ISSUE THREAD

**Issue by AlpinDale** [Darkempire78/OpenCalc#115]
I think this feature was added in the last update where entering a decimal point would add a 0 before the decimal, but it's bugged and takes effect for 2 digit numbers as well. For example, adding a decimal point after 10 makes 100.

**Comment by Darkempire78** [comment]
Arz you using the v2.0.0-beta3 ? This issue should be fixed @AlpinDale

**Comment by AlpinDale** [comment]
Thanks, the update fixed it.
