### ISSUE TITLE
Percent Calculation doesn't work

### ISSUE THREAD

**Issue by Uniquely6958** [Darkempire78/OpenCalc#116]
When evaluating a percent, it should consider the value immediately preceding the '%' sign to be divided by 100.
So `100 * 95%` should equal `95`.

However, entering that into the calculator, we get `9,500`, or a straight multiplication.
![First](https://user-images.githubusercontent.com/117340672/206168685-ad6962de-d90b-4096-9da4-1ab8f6f9ad41.jpeg)

More interestingly, for larger values, the calculation gets even more bizarre.
So `1700 * 95%` should be `1,615`.
But the actual result is `2,745,500`, where `2,745,500 = 1,700 * 1,700 * 95`
![Second](https://user-images.githubusercontent.com/117340672/206168714-f68ce50c-4222-4fd8-8c11-7f606b412440.jpeg)

**Comment by GEROGIANNIS** [comment]
Hello there , i can not replicate the bug you are descibing.

![Screenshot_20221207-134735_Calculator_1.png](https://user-images.githubusercontent.com/54914456/206172227-56400819-72a8-4f41-8938-bc16449677b9.png)

![Screenshot_20221207-134815_Calculator_1.png](https://user-images.githubusercontent.com/54914456/206172254-a141858e-28e5-4c3d-9f84-20c0f6812ab3.png)

What version of opencalc are you using?

**Comment by Uniquely6958** [comment]
It's v2.0.0-beta3 from fdroid.

**Comment by GEROGIANNIS** [comment]
> It's v2.0.0-beta3 from fdroid.

Im using v1.8.3 also from fdroid but i do not seem to have the bug 🤔

**Comment by Uniquely6958** [comment]
I got the same result after downgrading to v1.8.3 on fdroid so it isn't version specific.

I'm using Samsung on OneUI 4.1 with Android 12. Would that have anything to do with it?

**Comment by Uniquely6958** [comment]
The offending commit seems to be [https://github.com/Darkempire78/OpenCalc/commit/9d26dd7ebefce4aecebca6c884fcc2945ddc96e0](https://github.com/Darkempire78/OpenCalc/commit/9d26dd7ebefce4aecebca6c884fcc2945ddc96e0). 

Running the following: `getPercentString("100*95%")` returns `(100)*(100)*(95)%`, which gets further transformed into `(100)*(100)*(95)/100`, explaining the result.

I'm not an Android developer so what I said might be completely wrong.

**Comment by ac87** [comment]
@Darkempire78 I have created a branch https://github.com/Darkempire78/OpenCalc/commit/4a6be0fecb446625f438b76583679b902da0584a that I don't plan to PR, Maths is one of my biggest weaknesses.

However as you said you are new to Android development I think its useful to give you an idea of how unit tests work. I think you'd benefit greatly from having unit tests for the calculations.

**Comment by Darkempire78** [comment]
> @Darkempire78 I have created a branch [4a6be0f](https://github.com/Darkempire78/OpenCalc/commit/4a6be0fecb446625f438b76583679b902da0584a) that I don't plan to PR, Maths is one of my biggest weaknesses.
> 
> However as you said you are new to Android development I think its useful to give you an idea of how unit tests work. I think you'd benefit greatly from having unit tests for the calculations.

Thanks, I will add unit test during the week

**Comment by Darkempire78** [comment]
It should be fixed in the v2.0.0-beta7 (https://github.com/Darkempire78/OpenCalc/releases/tag/v2.0.0-beta7)
