### ISSUE TITLE
Adding decimal point without preceding 0 multiplies all previous values by 10

### ISSUE THREAD

**Issue by Uniquely6958** [Darkempire78/OpenCalc#117]
**Version:** v2.0.0-beta3

## Steps to reproduce:

1. Enter the following:
      `1.1 * 2.2 *`
2. Add a decimal point (without a leading 0)

Results: Figures change to `10.1 * 20.2 * 0.`
The initial numbers should not be multiplied by 10.

**Comment by Darkempire78** [comment]
The problem is that it replaces every "." by "0."

**Comment by Darkempire78** [comment]
It should be fixed now
