### ISSUE TITLE
Inverse trigonometric functions result in NaN

### ISSUE THREAD

**Issue by toschoch** [Darkempire78/OpenCalc#119]
Version v2.0.0-beta
Observed ind DEG mode:

arcsin(0.5) -> NaN but is expected to yield 30 
arccos(1) -> NaN should be 0
arctan(0.25) -> NaN

**Comment by Darkempire78** [comment]
> This is important

I'm not saying otherwise, but I don't know what it's due to...

**Comment by Joppla** [comment]
Hi, will this bug be solved soon?

**Comment by Darkempire78** [comment]
> Hi, will this bug be solved soon?

Yes, I will try to fix in during the weekend

**Comment by Joppla** [comment]
Thanks!
