### ISSUE TITLE
Results right bound, hence scrolling necessary

### ISSUE THREAD

**Issue by Aircan** [Darkempire78/OpenCalc#12]
Bug:
Calculating 1/3 = 3333333333
You have to scroll to the left to see 3.333333...
So right binding is useless. And too many digits after comma, too.
Talking about portrait mode

**Comment by Vanillj** [comment]
The first part can be solved by changing the parameter of the following line to `0` instead of `input.text.length`. https://github.com/Darkempire78/OpenCalc/blob/629d86c27ce96ce38629f553e4b066b913cee985/app/src/main/java/com/darkempire78/opencalculator/MainActivity.kt#L425

**Comment by Leif-W** [comment]
If a result would overflow, dynamically reduce font, to a minimum base size, else optionally wrap long lines after minimum font size reached, up to a maximum number of lines, then if still overflow, dynamically give a UI indicator or more to look at (i.e. translucent down arrow), and allow vertical scrolling.  At least for me, this is generally the UI pattern I would expect and most appreciate.  Variations on the idea, and incremental improvements welcome.

**Comment by lonelytheraphosidae** [comment]
I mean, we could show "..." to show that it continues and then if one taps. It popups with the whole number.

**Comment by Aircan** [comment]
I really think nobody needs more than 7 digits behind comma

**Comment by Darkempire78** [comment]
> The first part can be solved by changing the parameter of the following line to `0` instead of `input.text.length`.
> 
> https://github.com/Darkempire78/OpenCalc/blob/629d86c27ce96ce38629f553e4b066b913cee985/app/src/main/java/com/darkempire78/opencalculator/MainActivity.kt#L425 @Vanillj 

We cannot use that, because it will set the cursor at th first position. 
We want to scroll to the beginning of the EditText, but keep the cursor at the end of the calculation

**Comment by Darkempire78** [comment]
Fixed 721e83cacd655d58f9624a5849181172d4f61cc4
