### ISSUE TITLE
Design: Button Text Alignment. Material Menus

### ISSUE THREAD

**Issue by ac87** [Darkempire78/OpenCalc#124]
More design questions than a bug.

Firstly awesome work, really good to see a replacement to AOSP calculator that looks modern.

I was trying to align the text more centrally in the buttons, this is most obvious with ( ) ^ . buttons. Because the font padding its not really possible using text, thoughts on using vector drawables instead for the buttons?

Before / After
![full](https://user-images.githubusercontent.com/20557626/206852146-2b90e504-9541-4091-9600-bf1cbe23c60f.png)
The offset on the + and ( ) look more noticeable once the buttons get squashed. 
![expanded](https://user-images.githubusercontent.com/20557626/206852149-3d7c2e74-5d12-4e63-91f3-a201f637035e.png)

Note, I also tweaked the material color for the regular buttons, but I think I went one too far. Obviously the vector drawables can be tweaked/padded.

Another thing I've noticed is the menus aren't nicely rounded as you'd expect. 

![image](https://user-images.githubusercontent.com/20557626/206852243-cf2dca4b-ffad-4f59-bdf2-4a176620f852.png)

I put this down to you are basing the themes on AppCompat not Material3. Any objection to it being reworked so the menus will appear in Material theme? I think the `com.google.android.material` library gives you backwards compatibility to your min API 21 version.

**Comment by Darkempire78** [comment]
> I put this down to you are basing the themes on AppCompat not Material3. Any objection to it being reworked so the menus will appear in Material theme? I think the com.google.android.material library gives you backwards compatibility to your min API 21 version.
No, you are right, we should change appCompat to material. I used AppCompact because OpenCalc is my first Android app, I didn't know anything about it so I took it by default

**Comment by Darkempire78** [comment]
> I was trying to align the text more centrally in the buttons, this is most obvious with ( ) ^ . buttons. Because the font padding its not really possible using text, thoughts on using vector drawables instead for the buttons?
> The offset on the + and ( ) look more noticeable once the buttons get squashed.

It really does makes it look better!

**Comment by Darkempire78** [comment]
> Note, I also tweaked the material color for the regular buttons, but I think I went one too far. Obviously the vector drawables can be tweaked/padded.

It looks good but it is a little bit too dark. However I agree that defautl button's color have to be reworked

**Comment by GEROGIANNIS** [comment]
I have also noticed that the theme menu selection is always white, it might be better to change its color so its the same with the theme you pick.

![Screenshot_20221210-151925_Calculator_1.png](https://user-images.githubusercontent.com/54914456/206857308-49255bfd-a7b1-475e-9902-f4744bd32c8e.png)

**Comment by ac87** [comment]
@Darkempire78 For a first app this is really good work, hopefully I can help with a few pointers

Have pushed a start to my fork if you are interested in the icon changes. https://github.com/Darkempire78/OpenCalc/compare/main...ac87:OpenCalc:vector-icon-buttons

I dropped the regular buttons from `material_dynamic_neutral30` to `material_dynamic_neutral20` now, instead of 10 in the screenshots.

**Comment by Darkempire78** [comment]
@ac87 It seems good but the problem with the decimal separator is that it changes depending the language, idk if there are other optiond than only comma and dot

**Comment by Darkempire78** [comment]
> @ac87 It seems good but the problem with the decimal separator is that it changes depending the language, idk if there are other options than only comma and dot

From wikipedia only dot and comma seem to be used
https://en.wikipedia.org/wiki/Decimal_separator?wprov=sfla1

**Comment by ac87** [comment]
@Darkempire78 I could also only find two separators. Was a bit worried about that one too.

Just committed some more rework on that branch, had a bit of a headache getting themes to work as I'd expect them to. Basically using dark selectors for colors and style.

The result is the designer in Android Studio now works correctly as Dark is not a theme in its own right.
![image](https://user-images.githubusercontent.com/20557626/206876994-6b97837b-783a-4b51-865f-140aa50f0ee2.png)
![image](https://user-images.githubusercontent.com/20557626/206877003-dffc8f92-1e3f-4f9d-8fa2-44bb2a577089.png)

It makes the theme selection more complicated although now you can force light/dark on Material You theme as well.
![image](https://user-images.githubusercontent.com/20557626/206877069-080eb2e4-123b-4cba-b123-a58a8d821c32.png)

Because the correct base theme is used a lot less colors need to be overridden so menus appear to follow the dark/light mode.

I'm hoping now that changed AppCompat to Material is easier now. As that dialog still hurts my OCD as its not rounded and pretty!

**Comment by Darkempire78** [comment]
I think that Dark/Light should be at the top of the popup

**Comment by ac87** [comment]
Just got this to the point it was working to be honest, previously you had 

- System - default theme that follows light/dark of system
- Light - default forced to light
- Dark - default forced to dark
- Amoled 
- Material You - that theme followed system only. Whilst I don't think this is a problem, testing it in dark/light is difficult without the toggle

The problem with the style selection is it obviously doesn't apply to AMOLED theme, that's why I put it underneath as it gets disabled if AMOLED.

**Comment by Darkempire78** [comment]
ok I understand, it's a little less intuitive than before

**Comment by ac87** [comment]
Agreed with that. Did think about if material supported switching default to material entirely but thought that was a step too far. Obviously can change it as you like.
