### ISSUE TITLE
Application doesn't change the expression mark after clicking different ones in order

### ISSUE THREAD

**Issue by pm4rcin** [Darkempire78/OpenCalc#126]
Hi, not sure if title is correct but I hope you can clearly see what's going on from the screenshot below. I'm using 2.0.3 from f-droid but it was present on 1.8.3 too.
<details><summary>Screenshot</summary>

![signal-2022-12-10-192547_002](https://user-images.githubusercontent.com/37148802/206870134-a099a8de-0328-4d32-96b4-c06a5adaef2a.png)
</details>

**Comment by Darkempire78** [comment]
I do not really understand, you calculation is wrong what do you want ?

**Comment by pm4rcin** [comment]
I have attached video below. The problem is that it's unexpected to add infinite number of expression marks. They should change when you click any of them. Because otherwise the calculation results in garbage output (which is expected given input).
<details><summary>Video</summary>


https://user-images.githubusercontent.com/37148802/206870842-2d05043e-e2c8-48d3-ad68-59dff2dbb59f.mp4
</details>

**Comment by Darkempire78** [comment]
Oh okay I see, it's not a bug but an improvement
