### ISSUE TITLE
Functions don't act as a single token

### ISSUE THREAD

**Issue by Tanmandal** [Darkempire78/OpenCalc#129]
Using the cross button after using trigonometric functions removes 1 alphabet at a time instead of the full function
![Screenshot_2022-12-14-09-10-46-769_com darkempire78 opencalculator](https://user-images.githubusercontent.com/93572359/207499884-0a203cb8-129d-4161-90d3-a606a0a252f8.jpg)
![Screenshot_2022-12-14-09-10-55-615_com darkempire78 opencalculator](https://user-images.githubusercontent.com/93572359/207499896-0bb3eafa-70ce-4815-9474-f1768ac6e3ed.jpg)

**Comment by Darkempire78** [comment]
What is the version of OpenCalc ?

**Comment by Darkempire78** [comment]
@Darkempire78 What is your version of OpenCalc ?

**Comment by Tanmandal** [comment]
> @Darkempire78 What is your version of OpenCalc ?

1.8.3
![Uploading Screenshot_2022-12-16-08-26-27-186_com.darkempire78.opencalculator.jpg…]()
