### ISSUE TITLE
Separator (,/.) for large numbers?

### ISSUE THREAD

**Issue by Icy-Thought** [Darkempire78/OpenCalc#13]
Large numbers **MUST** have a separator for one to easily distinguish between thousands, millions, billions or whatever numbers you are working with.

How Google Calculator does it:
![Screenshot_20220730-132904_Calculator.jpg](https://user-images.githubusercontent.com/53710398/181908874-715e4603-00de-4484-b85f-7b57dafae4c0.jpg)

Also, you could add an opt-in `<space>` separator for decimal numbers (1 space per 3 numbers) to reduce the overcrowded output.

**Be aware** of which number separator you choose, not all countries use the same number separator!

**Comment by vairag22** [comment]
> Be aware of which number separator you choose, not all countries use the same number separator!

Google Calculator only supports the international scheme, i.e., comma after every 3 units from right-to-left, so supporting that should be prioritized. Other popular schemes like the Indian grouping scheme can be added later.

**Comment by Icy-Thought** [comment]
> And AFAIK only comma is used for grouping, internationally.

It depends on the country's numeral system and their use of delimiters. Example

Example (spanish):

**Comment by vairag22** [comment]
> Example: 1,000 (English thousand) equals 1.000 (Swedish thousand)

This grouping scheme is applicable in mathematics?

**Comment by vairag22** [comment]
Isn't `.` as decimal point internationally recognized? What do swedes use for denoting decimal point, comma?

**Comment by Darkempire78** [comment]
Done v1.5.0
