### ISSUE TITLE
Change types from Double to BigDecimal

### ISSUE THREAD

**Issue by l3u** [Darkempire78/OpenCalc#130]
Hi devs,

first of all thanks for this beautiful calculator!

Using v2.0.0-beta3 from F-Droid, there are apparently some problems with the well-known way computers do calculations internally. E.g. when you do 82.55x3, you get 247.6499999999…, where one of course should get 247.65.

![Screenshot_20221216-141939](https://user-images.githubusercontent.com/6770781/208108133-d099ea9b-e578-43e1-a858-44a0ddffe14b.png)

Thanks in advance for fixing this!

**Comment by Darkempire78** [comment]
This issue is due to double that round the values, it is necessary to change to the BigDecimal type but it causes problems. I made another branch with BigDecimal. I'll try to fix it

**Comment by l3u** [comment]
Thanks for the reply in no time! Alas, I'm completely out when it comes to Java or Kotlin. When it's about Android development, I'm only an end-user :see_no_evil:

However, thanks for providing this, I'm glad about each and every piece of software I can use to replace the stock Google apps!

**Comment by vsrt89** [comment]
I'm getting precision loss on addition operation (1.39+2.25) as well.

As for fix - maybe you'll find some inspiration from another implementation of Calculator app for Andorid:
https://github.com/SimpleMobileTools/Simple-Calculator/blob/master/app/src/main/kotlin/com/simplemobiletools/calculator/helpers/CalculatorImpl.kt#L256

![image](https://user-images.githubusercontent.com/118851310/213481039-ceabad18-471d-448b-9d61-fd1daa3f0582.png)

**Comment by Darkempire78** [comment]
It should be fixed now

**Comment by lefterisgar** [comment]
Unfortunately, it seems to cause #140.
