### ISSUE TITLE
Comma is shifting

### ISSUE THREAD

**Issue by El-Profesor77** [Darkempire78/OpenCalc#134]
After the first calculation, when adding a second calc, the comma shifts one digit to the right. See screen capture.
![IMG_20230111_061514](https://user-images.githubusercontent.com/122447278/211792586-78a85580-c2ed-45ab-bc47-e551d9feabe8.jpg)

**Comment by Darkempire78** [comment]
What is your app version ?

**Comment by El-Profesor77** [comment]
v2.0.0-beta3
11 janvier 2023 16:32 "Darkempire" ***@***.*** ***@***.******@***.***>)> a écrit:
What is your app version ? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID:    (https://duckduckgo.com/-fXqoPcsLeNkjX8k6D6HWo-NlG2KvkNF-luJiy0vFDfjdhMofPYdbfjuGQCnAt5FxI_tiR11o2d8TePUJDhJaPVxS3j8d8CEW-ryVv5ifvWN4haL-RsxZA_wWfgJ4CKPGTSaCnZdfoXqiD_Y0yDBiAAYRc2dTjfanGI-fRiwoDw)
	DuckDuckGo removed 1 tracker.
	More →
	What is your app version ?

**Comment by Darkempire78** [comment]
It should be fixed in the beta4
