### ISSUE TITLE
incorrect loading of values from history

### ISSUE THREAD

**Issue by N3koSempai** [Darkempire78/OpenCalc#136]
In this calculator units above 999 receive one point . example:
1.000
they look like this in the history as well but when retrieving from the history the dot is replaced by a comma converting the numbers to decimal.
normal operation:
![Screenshot_2023-01-13-18-38-26-16_7b7a71e2662e0d1cbba227111d207c2e.jpg](https://user-images.githubusercontent.com/43711237/212438121-63c3ba8e-7f56-4c08-a6a5-af93e5cc8631.jpg)

when loading from history:
![Screenshot_2023-01-13-18-38-56-83_7b7a71e2662e0d1cbba227111d207c2e.jpg](https://user-images.githubusercontent.com/43711237/212438130-d47177c8-16c4-42e2-850f-33a25517d986.jpg)

**Comment by Darkempire78** [comment]
What is the language of your phone ?

**Comment by N3koSempai** [comment]
spanish
