### ISSUE TITLE
Loading calculation from history crashes app

### ISSUE THREAD

**Issue by ctntt** [Darkempire78/OpenCalc#137]
If you load a calculation with a decimal point from history without taping 'AC' first, so that a number with a decimal point is appended to another number with a decimal point, it crashes the app.

Steps to reproduce:
1. Open app
2. Enter 0.3x0.3
3. Press on '='
4. Load calculation from history
5. App crashes

Expected behavior:
Either clear screen before loading calculation or put braces around the first expression (0.09)0.3x0.3

Version: v2.0.0-beta3
OS: Android 12

https://user-images.githubusercontent.com/115667885/213022221-aa7ecee5-0e38-4bf5-ac62-d53d2144df11.mp4

**Comment by ctntt** [comment]
``

**Comment by lefterisgar** [comment]
I think the issue has been fixed in v2.0.0-beta4. Could you try updating and see if the issue persists?

**Comment by ctntt** [comment]
Yes, the issue has been fixed in v2.0.0-beta4.

**Comment by ctntt** [comment]
There is a similar issue in v2.0.0-beta4 that wasn't there in version v2.0.0-beta3.

1. Press on any of the following buttons: (), ^, ÷, ×, +, -, √, π, %, !, sin, cos, tan, e, ln or log
2. Load calculation from history with a result containing a decimal point
3. App crashes

Also if you enter a expression with a decimal point (f.e. 0.2) then press on any of the buttons mentioned in 1. and load a floating point result from history (f.e. 0.3) it results in 0(0.2)0.3 instead of f.e. 0.2-0.3 .

And if you type f.e. 2 then - and load 0.3 from history it results in 220.3 instead of 2-0.3 .

Version: v2.0.0-beta4
OS: Android 12

**Comment by lefterisgar** [comment]
True, I was able to replicate both of them! Make sure to open a bug report!
