### ISSUE TITLE
Large numbers are freezing the app

### ISSUE THREAD

**Issue by GhostOfVodka** [Darkempire78/OpenCalc#14]
Large numbers calculations, like 9999^9999 cause app to freeze deadly and then crash it, despite "Infinity" answer displays.

https://user-images.githubusercontent.com/110062862/181937798-d3d0d7a6-ad74-4aa3-8d9d-d375ef5660ef.mp4

**Comment by kabirnayeem99** [comment]
Can I work on this @Darkempire78 ?

**Comment by Darkempire78** [comment]
Sure  @kabirnayeem99
