### ISSUE TITLE
Calculations with decimal digits are wrong

### ISSUE THREAD

**Issue by lefterisgar** [Darkempire78/OpenCalc#140]
**Describe the bug**
When doing calculations with decimal numbers the results are wrong, except when you hit the equals button. It might be a rounding error.

**To Reproduce**
Enter 1/10. Expected result is 0,1 but the output is 1.

Before pressing "=":
![Screenshot_20230124-225907_Αριθμομηχανή](https://user-images.githubusercontent.com/46350667/214412420-6ae75ebe-4b04-4583-bc6d-6e1013db82ae.png)
After pressing "=":
![Screenshot_20230124-225913_Αριθμομηχανή](https://user-images.githubusercontent.com/46350667/214412408-4c5f3358-0833-4572-8988-e853393d5d20.png)
Before pressing "=":
![Screenshot_20230124-225852_Αριθμομηχανή](https://user-images.githubusercontent.com/46350667/214412431-9f6d56b9-79db-43f4-bb0a-78af641fe176.png)
After pressing "=":
![Screenshot_20230124-225900_Αριθμομηχανή](https://user-images.githubusercontent.com/46350667/214412426-f3da20ef-6e65-40ae-af41-ed68377398cc.png)

**Comment by Darkempire78** [comment]
What is your app version ?

**Comment by lefterisgar** [comment]
The version is the latest as of now (v2.0.0-beta5) and the language is greek. This bug did not exist in beta4 however.

**Comment by Darkempire78** [comment]
It should be fixed in the v2.0.0-beta6 (https://github.com/Darkempire78/OpenCalc/releases/tag/v2.0.0-beta6)
