### ISSUE TITLE
Crash when typing decimal point

### ISSUE THREAD

**Issue by TheSunCat** [Darkempire78/OpenCalc#141]
Hi! I just found this app and really like it, thanks for maintaining it!
I have found that the app crashes when I attempt to insert a period at the start of an expression such as this one: `8.1`

**Comment by Darkempire78** [comment]
What is the version of your app and the language of your phone ?

**Comment by TheSunCat** [comment]
My phone is using English (US), and I'm using app version `2.0.0-beta3 (23)` from F-Droid.

**Comment by Darkempire78** [comment]
Can check if the bug is still present in the v2.0.0-beta5 please ?

**Comment by TheSunCat** [comment]
Sure! Where can I find this version? I'm using the latest published F-Droid build at the moment (`2.0.0-beta3`).

**Comment by Darkempire78** [comment]
> Sure! Where can I find this version? I'm using the latest published F-Droid build at the moment (`2.0.0-beta3`).

https://github.com/Darkempire78/OpenCalc/releases/tag/v2.0.0-beta5

**Comment by TheSunCat** [comment]
Thanks! This version fixes it (and I have learned that the release GitHub automatically shows is not the latest one... sorry!)
