### ISSUE TITLE
Add Weblate for translations

### ISSUE THREAD

**Issue by throwaway-d** [Darkempire78/OpenCalc#142]

**Comment by Darkempire78** [comment]
@throwaway-d To be honest, I have never used Weblate and I do not really understand how to configure it

**Comment by ngocanhtve** [comment]
I am also interested and would like to contribute a translation for my Vietnamese language. Currently I don't know how to contribute, and weblate I know how to use to contribute translations.

**Comment by throwaway-d** [comment]
> I am also interested and would like to contribute a translation for my Vietnamese language.

I am also going for my Vietnamese language!

**Comment by Darkempire78** [comment]
Done! The link : https://hosted.weblate.org/engage/opencalc/

**Comment by throwaway-d** [comment]
Yeah!
