### ISSUE TITLE
App crashes on undefined logarithm

### ISSUE THREAD

**Issue by lefterisgar** [Darkempire78/OpenCalc#143]
**Describe the bug**
OpenCalc will crash when an undefined logarithm is typed, instead of outputting an error.

**To Reproduce**
Enter 'ln0' or 'log0'

**Expected behavior**
Print an error message, informing the user that log 0 is undefined. It's not a real number, because you can never get zero by raising anything to the power of anything else.

EDIT: Maybe a test should also be added so that it won't happen again?

**Comment by Darkempire78** [comment]
Fixed 9be97c4e2a27787ec02b47d18ae8946394c3832c

**Comment by Darkempire78** [comment]
It should be fixed in the v2.0.0-beta6 (https://github.com/Darkempire78/OpenCalc/releases/tag/v2.0.0-beta6)
