### ISSUE TITLE
Fix floating-point rounding errors

### ISSUE THREAD

**Issue by n-ivkovic** [Darkempire78/OpenCalc#149]
**Describe the bug**
Floating-point numbers, such as the `double` type used in this app, are susceptible to rounding errors due to how floating-point numbers work. This is a well-known issue and is commonly handled.

As they are not handled in this app, the displayed results of equations that use fractional values will be different from the expected result.

**To Reproduce**
Calculate any of the below equations:
- 0.1 + 0.2
- 0.9 - 0.8
- 10 × 0.035

The above equations will produce the following results:
- 0.30000000000000004
- 0.09999999999999998
- 0.35000000000000003

**Expected behavior**
The above equations should produce the following results
- 0.3
- 0.1
- 0.35

**Screenshots/videos**
![Screenshot_20230202-064607.png](https://user-images.githubusercontent.com/39162564/216147712-d82f1999-a3c5-4b91-9522-412a286d51a3.png)
![Screenshot_20230202-064617.png](https://user-images.githubusercontent.com/39162564/216147765-e360227b-b5a2-4a38-acc7-5d307d545a5e.png)
![Screenshot_20230202-064628.png](https://user-images.githubusercontent.com/39162564/216147825-9a8f8028-017a-4e66-9521-e595f416be4a.png)
![Screenshot_20230202-064644.png](https://user-images.githubusercontent.com/39162564/216147868-8489cac7-f568-4ff9-a53a-f96791479889.png)
![Screenshot_20230202-064654.png](https://user-images.githubusercontent.com/39162564/216147906-d7801b74-341b-4323-a061-d2671ff5d9fb.png)
![Screenshot_20230202-064719.png](https://user-images.githubusercontent.com/39162564/216147928-6e1fdd74-39e5-46dd-843f-1e0f722334e5.png)
![Screenshot_20230202-064733.png](https://user-images.githubusercontent.com/39162564/216147951-489f0262-2b40-4dd0-91be-521fe942cd3a.png)

**Smartphone (please complete the following information):**
 - Device: Sony Xperia 10 3 (XQ-BT52)
 - OS: Android 12
 - Version: v2.0.0-beta3
 - Language: English

**Additional context**
I don't know much about Java or Kotlin, but it seems Java's `BigDecimal` class can be used to resolve the issue.
- https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/java.math.-big-decimal/
- https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/to-big-decimal.html

**Comment by Darkempire78** [comment]
Already fixed, install the latest version (v2.0.0-beta6 https://github.com/Darkempire78/OpenCalc/releases/tag/v2.0.0-beta6)
