### ISSUE TITLE
Decimal separator multiplies by 10

### ISSUE THREAD

**Issue by juanjgit** [Darkempire78/OpenCalc#151]
**Describe the bug**
It you multiply a number that included decimals by a decimal number less that 1 omitting the initial "0", the previous number is increased by 10 

**To Reproduce**
Maybe it is related to regional settings, I tried this in a Spanish phone that uses "," as decimal separator, not "."
1. Type any decimal number. Ie: "123,4"
2. Type the multiply symbol  "x"
3. Type a decimal number but without the initial "0". Ie: ",1" (instead of "0,1")
4. See that the previous number is increased by x10, so In this example, the result is  "123,040000000000002"  (also additional error is introduced, but that should be another bug)

**Expected behavior**
123,4 x ,1 = 123,4 x 0,1 = 12,34

**Screenshots/videos**

**Smartphone (please complete the following information):**
 - Device:  OnePlus
 - OS: Android 11
 - Version 2.0.0-beta3
 - Language Spanish

**Additional context**

**Comment by Darkempire78** [comment]
It should be fixed in the latest version (v2.0.0-beta7 https://github.com/Darkempire78/OpenCalc/releases/tag/v2.0.0-beta7)

**Comment by juanjgit** [comment]
Tested v2.0.0-beta7 and it is fixed. Thank you!
