### ISSUE TITLE
Problem with factorial function

### ISSUE THREAD

**Issue by Domefemia** [Darkempire78/OpenCalc#166]
**Describe the bug**
If I try to do the factorial of a negative number instead of giving me Nan as result it give the factorial of the number as it was a positive number but negative, for example if try to do -5! it give me -120. 

And I also wanted to report that instead of giving Nan as it's currently written in the code 0! should give as a result 1.
https://www.thoughtco.com/why-does-zero-factorial-equal-one-3126598

**To Reproduce**
1. Press the minus button
2. Press a random number
3. Then click the factorial button

**Expected behavior**
-5! should give me as a result Nan

**Screenshots/videos**
https://media.discordapp.net/attachments/831525884069675067/1076231040437342319/IMG_20230217_205730.jpg

**Smartphone (please complete the following information):**
 - Device: Poco x3 nfc
 - OS: Android 12, miui 13.0.4
 - Version: 2.0.0 from f-droid
 - Language: Italian

**Comment by Darkempire78** [comment]
-5! is like -(5!), but you are right, (-5)! gives -120 instead of NaN

**Comment by Domefemia** [comment]
But it does this in any case even if the -5 is a result of a previous operation

**Comment by lefterisgar** [comment]
Also if you type (5)! it will give you 5. Probably related. For some reason, when there are parentheses before the ! symbol, the code doesn't reach the factorial function.

**Comment by Darkempire78** [comment]
I fixed factoriel of 0

**Comment by Darkempire78** [comment]
Done
