### ISSUE TITLE
Calculation issues

### ISSUE THREAD

**Issue by MillionsToOne** [Darkempire78/OpenCalc#171]
**Can't use addition, multiplication, division or caret on the answer without pressing substraction**

**1. Make a calculation
   2. Click on "="
   3. Try to press anything of those mentioned above without pressing substraction**

**Use multiply, division, addition and caret on answer without having to press substraction first**

**https://drive.google.com/file/d/1_wZGUYNFRa5ItFszhFZ5gs2DVTdFBMao/view?usp=share_link**
If applicable, add screenshots or videos to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [Oneplus 8T]
 - OS: [LineageOS based on Android]
 - Version [LineageOS 20, Android 13]
 - Language [English]

**Additional context**

**Comment by lefterisgar** [comment]
I pushed a change that probably fixes it. @Darkempire78 can you provide some feedback on whether it works or not?
