### ISSUE TITLE
Consider adding Open Collective as another donation option

### ISSUE THREAD

**Issue by throwaway-d** [Darkempire78/OpenCalc#174]
#### :loudspeaker: The Shortcoming
1. PayPal is proprietary and PayPal shares the data collected from customers with over 600 other companies
2. Buy Me a Coffee is also proprietary and privacy-invasive
3. Open Collective is open source, transparent, private and designed for FLOSS projects 
#### :pencil: Additional context
Examples of some projects that use Open Collective:

- https://opencollective.com/LocalCDN
- https://opencollective.com/darkreader
- https://opencollective.com/gitea
- https://opencollective.com/libredirect

**Comment by Darkempire78** [comment]
I cannot create an Open Collective page because the project is on my private profile and not on an organization...

**Comment by throwaway-d** [comment]
> I cannot create an Open Collective page because the project is on my private profile and not on an organization...

Oh… :(
