### ISSUE TITLE
when long pressing on a digit to create a small version of that digit

### ISSUE THREAD

**Issue by Wjxfi** [Darkempire78/OpenCalc#176]
small numbers are very important in math, and they are not here.

**Comment by Darkempire78** [comment]
Why not add this feature but I don't know if it's very useful. Are there other people interested in this feature?

**Comment by Darkempire78** [comment]
I say that because you can already use `^`

**Comment by Darkempire78** [comment]
Vote here please #180

**Comment by Darkempire78** [comment]
To be sure, what do you mean by "small numbers" ? subscript ? superscript ?
