### ISSUE TITLE
Cryptocurrency for donations

### ISSUE THREAD

**Issue by Wjxfi** [Darkempire78/OpenCalc#177]
my issue at the link: https://github.com/yogeshpaliyal/KeyPass/issues/332

**Comment by Darkempire78** [comment]
I do not have any crypto. I don't really know how it works, is it complicated? what should I do?

**Comment by hbread00** [comment]
Simply generate an "address, public key, private key" through any cryptocurrency wallet and then provide that "address" on the donation page.

**Comment by hbread00** [comment]
> I do not have any crypto. I don't really know how it works, is it complicated? what should I do?

Simply generate an "address, public key, private key" through any cryptocurrency wallet and then provide that "address" on the donation page.

**Comment by Darkempire78** [comment]
I will if I use crypto-currencies one day
