### ISSUE TITLE
Selective history delete

### ISSUE THREAD

**Issue by strider72** [Darkempire78/OpenCalc#178]
Feature request: rather than clearing the entire history, I would like the ability to swipe a single history entry to delete it. :-)

Good app. Thanks!

**Comment by inson1** [comment]
Its good feature, but I think it should be optional. Idk what should be the default.

**Comment by Darkempire78** [comment]
> Its good feature request, but I think it should be optional. Idk what should be the default.

I agree with you

**Comment by Darkempire78** [comment]
Done
