### ISSUE TITLE
Release to PlayStore

### ISSUE THREAD

**Issue by n-ce** [Darkempire78/OpenCalc#18]
and become the best alternative to proprietary GoogleCalc.

Either that Or reduce the app size by offering
- SplitAPKs Support
- Specific Arch Support

**Comment by bonswouar** [comment]
I've just done a quick basic test about generating multiple APKs for dpi/arch, and apparently it doesn't make a big difference for this project, about 0.1MB less only
But there are probably some other optimizations I don't know

**Comment by n-ce** [comment]
If that's the case then I guess google calculator is coded in java instead of kotlin.
Don't know any other ways they managed to keep it below 3MB.

**Comment by julianfairfax** [comment]
> If that's the case then I guess google calculator is coded in java instead of kotlin. Don't know any other ways they managed to keep it below 3MB. If this app reaches below 4MB, that is enough of a milestone.

Why is the app being above 4MB an issue?

**Comment by pc00per** [comment]
> Why is the app being above 4MB an issue?

It's not about space constraints. It's about minimizing the unnecessary graphical elements & codebase. Devs should always thrive for efficient project build, no matter how small & reasonable they are.

**Comment by Darkempire78** [comment]
I'm working on the release on the Google play store

**Comment by Darkempire78** [comment]
OpenCalc is available on the Play Store !
https://play.google.com/store/apps/details?id=com.darkempire78.opencalculator

**Comment by n-ce** [comment]
Please add the github repo link in the app description.

**Comment by n-ce** [comment]
@clementwzk The app isn't getting updated on PlayStore since v3.14

**Comment by clementwzk** [comment]
> @clementwzk The app isn't getting updated on PlayStore since v3.14

The last update is deployed only a 20% because it contains a scale bug. Next version will be available for everyone
