### ISSUE TITLE
Avast anti-virus flags this app as one that is 'suspicious'

### ISSUE THREAD

**Issue by Dao0fGeek** [Darkempire78/OpenCalc#19]
Avast anti-virus flags this app as one that is 'suspicious' and may 'harm your device'. Either the code needs to be audited or Avast needs to be informed of a false positive.

**Comment by Darkempire78** [comment]
Have you tested on your phone with Avast or is it on a pc?

**Comment by Dao0fGeek** [comment]
On my android phone. Not on pc.

**Comment by Darkempire78** [comment]
it must be because bacause you installed it with an apk and not from the Google Play I think. In any case application code is very simple and short if you want to read it

**Comment by Dao0fGeek** [comment]
I installed via F-droid installer.

**Comment by Darkempire78** [comment]
No idea

**Comment by Dao0fGeek** [comment]
Just my guess, but avast may be flagging new updates and installs from F-droid cuz it also flagged Sushi and Gurgle which I had installed previously via F-droid - so they may all have been flagged after they updated. I don't have any other explanation. Just trying to be a "good neighbor" cuz if I'm getting them flagged then other Avast users are too. I do see that virustotal's version of the avast engine doesn't flag it or the others so it's probably unique to the android version of Avast's engine.
