### ISSUE TITLE
Add support for iOS?

### ISSUE THREAD

**Issue by throwaway-d** [Darkempire78/OpenCalc#194]
Unlike iPhones, iPads don’t have Apple calculator preinstalled. https://piped.vern.cc/watch?v=WK_AtW66XI0

So OpenCalc would be great to have!

**Comment by Darkempire78** [comment]
I don't know if the application can be ported to IOS. Even so, I don't have any Apple device and I don't want to pay to publish the application.

**Comment by throwaway-d** [comment]
1.
> I don't know if the application can be ported to IOS.

Yes. Kotlin applications can be ported. https://kotlinlang.org/docs/multiplatform-mobile-integrate-in-existing-app.html

2.
> I don't want to pay to publish the application.

a. You can release the `.ipa` file on GitHub Releases and package managers so at least jailbroken users can use it.
b. You can try TestFlight. https://github.com/yattee/yattee/wiki/Installation-Instructions#all-platforms-testflight
c. You can try AltStore. https://github.com/yattee/yattee/wiki/Installation-Instructions#iostvos-altstore
