### ISSUE TITLE
Some results with % are not correct

### ISSUE THREAD

**Issue by Tvirin** [Darkempire78/OpenCalc#196]
1 example:

900÷10% = **0.1 incorrect**
900÷10% = **9000 correct**

---

2 example:

1000%10 = **0.0999000999 incorrect**
1000%10 = **100 correct** 
Should be (1000%)×10

---

3 example:

2%2% = **1.996008E-5 incorrect**
2%2% or (2%)×(2%) = **0,0004 correct**

**Comment by ngocanhtve** [comment]
Example:
OpenCacl: 1÷0.000,000,000,001% = **0** = incorrect
OpenCacl: 1÷10^(14) = **0** = incorrect
OpenCacl: 1÷0.0000000001% = **1×10^(-12)** = incorrect
OpenCacl: 1÷0.1% = **0.001** = incorrect

**Comment by Darkempire78** [comment]
Fixed :
✅ 1000%10 = 0.0999000999 incorrect
✅ 2%2% = 1.996008E-5 incorrect

Not fixed : 
❌ 900÷10% = 0.1 incorrect
