### ISSUE TITLE
Weblate: Can you please make read-only strings blue?

### ISSUE THREAD

**Issue by throwaway-d** [Darkempire78/OpenCalc#197]
It would be easy to differ with editable strings.

Example: https://hosted.weblate.org/projects/f-droid/f-droid/vi/

**Comment by Darkempire78** [comment]
@lefterisgar Do you know how to do that ? I did not find the setting. The Weblate interface is not really intuituive

**Comment by lefterisgar** [comment]
@Darkempire78 I'm not sure if it's even possible to do that. I've checked other projects on Weblate and it's the same.

**Comment by throwaway-d** [comment]
> I'm not sure if it's even possible to do that. I've checked other projects on Weblate and it's the same.

So how did [F-Droid](https://hosted.weblate.org/projects/f-droid) have that?

**Comment by lefterisgar** [comment]
Maybe it was given automatically because if you see, they have a lot of categories.
For example, take a look here: (it's by F-Droid)
https://hosted.weblate.org/projects/f-droid/fdroiddata/af/

**Comment by Darkempire78** [comment]
I close for the moment

**Comment by throwaway-d** [comment]
I will ask Weblate about this.

**Comment by throwaway-d** [comment]
@github-actions destroyed my hopes and dreams!

**Comment by throwaway-d** [comment]
Now real humans have restored my hopes and dreams!

**Comment by Darkempire78** [comment]
?

**Comment by throwaway-d** [comment]
> ?

@Darkempire78 If you’re asking about the now deleted 2 above comments, those were just my really pointless expressions. I’ve deleted those.

If you’re asking about the current state of this issue, I would say that this issue depends on the upstream. We need to wait Weblate deciding.
