### ISSUE TITLE
Replace `.png` with `.webp`

### ISSUE THREAD

**Issue by throwaway-d** [Darkempire78/OpenCalc#198]
`.webp` has same quailty as `.png` but loads more efficently.
1. https://en.wikipedia.org/wiki/WebP
2. https://developers.google.com/speed/webp/docs/webp_study

**Comment by Darkempire78** [comment]
Are you talking about the screenshots ? It does not really matter...

**Comment by throwaway-d** [comment]
All images in README.md and the application.

**Comment by throwaway-d** [comment]
> It does not really matter...

Performance is really matter.

**Comment by Darkempire78** [comment]
I'll do that when I update the screenshots. By the way, the .png's in the application will be removed when the about page is redesigned

**Comment by throwaway-d** [comment]
BTW, once you replaced, I would also make a PR for README.md (also related to images). I would like to wait until you replace so I wouldn't have to deal with conflicts

**Comment by throwaway-d** [comment]
@Darkempire78 I don’t notice any changes?
