### ISSUE TITLE
Resize the result so you don't have to scroll

### ISSUE THREAD

**Issue by Tvirin** [Darkempire78/OpenCalc#199]
Resize the result so you don't have to scroll

![11](https://user-images.githubusercontent.com/93820884/221445900-3f6d0cef-283b-4813-9ebf-d25d375b6749.png)

**Comment by inson1** [comment]
I dont like that idea. Result number is already small imo.

**Comment by Darkempire78** [comment]
Yes, it does not make sens since we added an option to customize the numner of decimal
