### ISSUE TITLE
Light splash screen

### ISSUE THREAD

**Issue by julianfairfax** [Darkempire78/OpenCalc#20]
Despite having the Material You theme enabled and dark mode enabled on my phone, the splash screen is always light. This can be blinding and should be fixed

**Comment by Darkempire78** [comment]
It must be fixed with the [1.3.1](https://github.com/Darkempire78/OpenCalc/releases/tag/1.3.1)

**Comment by julianfairfax** [comment]
It's not. I'm talking about this screen when you open the app. It's bright white even in dark mode

![Screenshot_20220804-080450](https://user-images.githubusercontent.com/43753131/182774815-6fbb26c9-5485-43ec-918d-c4ca280e1d9b.png)

**Comment by Darkempire78** [comment]
Oh ok my bad

**Comment by julianfairfax** [comment]
A simple fix would be to always use a dark splash screen, but it must be possible to use one that is just light or dark based on system theme or theme set in the app?

**Comment by Darkempire78** [comment]
> A simple fix would be to always use a dark splash screen, but it must be possible to use one that is just light or dark based on system theme or theme set in the app?

It seems to be impossible x)
So I have defined dark background by default. Another option is to change the background color for the blue of the icon, but it seems to be a little bit light
