### ISSUE TITLE
Division by Functions 

### ISSUE THREAD

**Issue by brainded-boi** [Darkempire78/OpenCalc#200]
**Describe the bug**
Calculator cannot divide by Functions like log, sin, tan etc, even after using ()'s

**Screenshots/videos**
![Screenshot_20230227-070916_Calculator](https://user-images.githubusercontent.com/96941634/221452773-88b82f6d-864b-4bab-bb9c-cf0b6cc8b1e7.png)
![Screenshot_20230227-070906_Calculator](https://user-images.githubusercontent.com/96941634/221452779-9fc0fc35-cbad-47cf-a8e1-f1225d78b982.png)
![Screenshot_20230227-071256_Calculator](https://user-images.githubusercontent.com/96941634/221452955-1128be37-e6af-48d4-9f50-9f0551614117.png)

**Smartphone (please complete the following information):**
 - Device: realme narzo 30a
 - OS: Android 11
 - Version: 2.1.2
 - Language: English

**Comment by Markus40** [comment]
Other probably related combinations that do not work:
1*(sin(2))
1+sin(2)
1-sin(2)
2^sin(2)
(sin(2))
