### ISSUE TITLE
Consider making an organization

### ISSUE THREAD

**Issue by throwaway-d** [Darkempire78/OpenCalc#202]
There are some benefits of forming a group of maintainers:

1. If the repo were only owned by an account not an organization and that account went inactive forever, the project must be forked to be continued.

2. Work will be faster since contributors can commit directly.

3. We can use Open Collective! #174

4. @weblate can commits directly to the repo so:
a. Translating is faster, simpler without the need of @lefterisgar force-pushing
b. The PR board wouldn't be bloated
_Example 1:_ https://codeberg.org/Hyperpipe/Hyperpipe/commits/branch/main
_Example 2:_ https://codeberg.org/LibRedirect/libredirect/commits/branch/master

**Comment by lefterisgar** [comment]
I think it's a good idea, but we have to ask @Darkempire78 for that. It would be also helpful if OpenCalc needs a separate repository for something in the future...

**Comment by lefterisgar** [comment]
But I'm not sure how easy it is to migrate and the main dev needs to focus on more important things right now IRL.

**Comment by throwaway-d** [comment]
Why did you decide not to, please?
