### ISSUE TITLE
sin(x!) and cos (x!) give wrong result

### ISSUE THREAD

**Issue by Markus40** [Darkempire78/OpenCalc#211]
**Describe the bug**
sin(5!°) should be sin(120°) ≈ 0.866 and not 0.956
If 120 is entered directly, the result is correct. Only when using 5! is there an error.

**Smartphone:**
 - Device: [Samsung Galaxy A52 5g]
 - OS: [Android 13]
 - Version [2.1.3]
 - Language [German]

**Comment by Markus40** [comment]
This also applies to tan.

**Comment by Markus40** [comment]
Errors occur not only with the faculty, but sometimes also when you calculate within the bracket, for example: arctan(2) ≈ 1,107 and arctan(1+1) ≈ 1,785

**Comment by Darkempire78** [comment]
> Errors occur not only with factorials, but sometimes also when you calculate within the bracket, for example: arctan(2) ≈ 1,107 and arctan(1+1) ≈ 1,785

Fixed

**Comment by Darkempire78** [comment]
Fixed
