### ISSUE TITLE
Better placement of parentheses inside existing calculations

### ISSUE THREAD

**Issue by Markus40** [Darkempire78/OpenCalc#213]
When modifying existing calculations, parentheses are always opened first and closed if there is an excess bracket to the left, even if it makes no sense to do so. Placing the closing/right parentheses first or using nested parentheses is tedious.

Ideally, parentheses should open towards a number and close away from an operator.

Even with the changes, it would be nice to be able to have separate buttons for right and left parentheses, or to split the existing button into two.

**Comment by Markus40** [comment]
Here a few cases that could cause problems.

When a new parentheses is placed between already existing parentheses it should also be open towards the next number and away from operators:
((1+2)*3)^2  -->  (((1+2)*3)^2

Multiplication by juxtaposition should be treated like normal multiplication. A new parentheses after the 2 should open to the right:
2(-1+3)  -->  2((-1+3)

**Comment by Darkempire78** [comment]
@Markus40 I updated the parenthesis system in the v2.1.4, can you test it please ? https://github.com/Darkempire78/OpenCalc/releases/tag/v2.1.4

**Comment by Markus40** [comment]
It still it still gets some wrong:
1+2×3 --> 1+2(×3
