### ISSUE TITLE
Math error moves cursor to the back

### ISSUE THREAD

**Issue by Markus40** [Darkempire78/OpenCalc#215]
**Describe the bug**
If a math error or divide by 0 error occurs and the cursor is in the middle of the calculation, the cursor will remain in place visually, but will move to the back when the backspace key is pressed.

**To Reproduce**
- Input: 1÷0
- Put cursor in front of ÷
- Press equal
- Press backspace
- 0 gets deleted instead of 1

**Expected behavior**
Do not move cursor and delete correct character.

**Smartphone:**
 - Device: [Samsung Galaxy A52 5g]
 - OS: [Android 13]
 - Version [2.1.3]
 - Language [German]

**Comment by Markus40** [comment]
This also applies to scientific funtions like sin and parentheses.

**Comment by Darkempire78** [comment]
Fixed at the same time than #217
