### ISSUE TITLE
Change app name to "Calculator"

### ISSUE THREAD

**Issue by vairag22** [Darkempire78/OpenCalc#22]
Please change the app name from "OpenCalc" to "Calculator", for convenience. Extra scrolling feels unintuitive for accessing essential utilities.

- Google's Calendar app is named "Google Calendar" on Play Store but only "Calendar" in app drawer. 
- Xiaomi's Calculator app goes by the name "Mi Calculator" on Play Store but only as "Calculator" in app drawer.

Doing same for this app would be appreciated.

**Comment by julianfairfax** [comment]
This is the same for Simple Calculator, which installs as "Calculator"

**Comment by Darkempire78** [comment]
Done 8cbd7c72a55fa1c4a1615ed917e4c04281a531f2
There is only English and French translation for the moment, you can add you own! (open an issue if you need help or a pull request to merge your translation)
