### ISSUE TITLE
Second multiplication and division do not work

### ISSUE THREAD

**Issue by Wjxfi** [Darkempire78/OpenCalc#221]
https://user-images.githubusercontent.com/113500363/223374614-37090542-1715-44f0-960f-676a47606c99.mp4

I wanted to do that, but it didn't work.
https://user-images.githubusercontent.com/113500363/223376418-8eb92dff-0763-4770-8664-4e6ee7e05c72.mp4

**Comment by Darkempire78** [comment]
it doesn't make sense, you have 555 and you want to get to 5÷6÷55, instead of adding "÷÷" and then changing it to "÷6÷", just add "÷6÷" in that order as it is logical to do
