### ISSUE TITLE
Use the comma button to slide through calculation + delete quickly with the backspace button

### ISSUE THREAD

**Issue by Wjxfi** [Darkempire78/OpenCalc#222]
https://user-images.githubusercontent.com/113500363/223375473-e7fb75b4-a672-42d9-9285-c106bebaea1f.mp4

**Comment by Darkempire78** [comment]
You want to use the comma button to slide through calculation ?

**Comment by Markus40** [comment]
I would also like to have such a function, it is quite useful.

It would also be great to be able to delete quickly with the backspace button:

https://user-images.githubusercontent.com/83376570/223418402-28acdeae-0007-424f-b1a1-ae381c757793.mp4
