### ISSUE TITLE
tan() does not work properly.

### ISSUE THREAD

**Issue by NikhilTomar3000** [Darkempire78/OpenCalc#229]
**Describe the bug**
tan() function does not work properly in both degree and radian mode.

**Screenshots/videos**
![Screenshot_2023-03-10-19-22-58-27_7b7a71e2662e0d1cbba227111d207c2e](https://user-images.githubusercontent.com/55707957/224334365-28e722d7-5864-4372-afe7-67793069fbeb.jpg)

![Screenshot_2023-03-10-19-22-50-73_7b7a71e2662e0d1cbba227111d207c2e](https://user-images.githubusercontent.com/55707957/224334473-304f3450-792d-4dcd-9bc5-e81cc7d5570a.jpg)

![Screenshot_2023-03-10-19-22-43-34_7b7a71e2662e0d1cbba227111d207c2e](https://user-images.githubusercontent.com/55707957/224334631-eb6f8c03-e970-4a28-bcee-18eef214d979.jpg)

**Smartphone (please complete the following information):**
 - Device: Realme 9 
 - OS: Android 12
 - Version 2.1.5
 - Language English

**Comment by EinoHR** [comment]
I'm on v2.1.5 and tan still gives totally wrong results! 

```
DEG mode

**Comment by Darkempire78** [comment]
> I'm on v2.1.5 and tan still gives totally wrong results!
> 
> ```
> DEG mode in OpenCalc
> tan(5) = -3.380515006247
> ```
> 
> ```
> DEG mode in AOSP Calc
> tan(5) = 0.0874886635
> ```
> 
> @Darkempire78 please fix?
> 
> Edit: Apparently my F-Droid installation doesn't show any new updates (even though the website says v2.3.1 is latest), sorry if this has been fixed already.

It's alrealdy fixed since the v2.1.6. You can download the lastest version here : https://github.com/Darkempire78/OpenCalc/releases/tag/v2.3.1
