### ISSUE TITLE
Smaller Font

### ISSUE THREAD

**Issue by HonestAbe7** [Darkempire78/OpenCalc#24]
Love the app but the font is too big. Please add a setting to reduce the font to make it smaller.

**Comment by vairag22** [comment]
Font size of what? of buttons or the calculation display area?

Slider should allow to users to increase as well decrease the font size.

**Comment by HonestAbe7** [comment]
The font size of the text at the top. I like the big buttons though.

**Comment by Darkempire78** [comment]
It is good on the v1.6.0 ?

**Comment by HonestAbe7** [comment]
Yes, the font size is much better. Thanks
