### ISSUE TITLE
Vibration option not working

### ISSUE THREAD

**Issue by heberjeur** [Darkempire78/OpenCalc#241]
**Describe the bug**
The vibration mode is currently not working besides I activated the option.
Users will not receive any haptic feedback when performing calculations.

**Screenshots/videos**
If applicable, add screenshots or videos to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: Samsung A50
 
![Screenshot_20230319-090506_LibreTube](https://user-images.githubusercontent.com/11852634/226161997-7f0a68ad-689f-4815-8562-99475154d9b5.jpg)

 - OS: Android 
 - Version 11
 - Language French

**Additional context**
It works correctly on the yetcalc open source app

**Comment by Darkempire78** [comment]
It's weird because it works well on my Pixel 6 (android 13)

**Comment by Tvirin** [comment]
This happens when if you have vibration feedback Disabled on the phone settings.
Which I think is normal

**Comment by Darkempire78** [comment]
@heberjeur can you confirm what @Tvirin said ? Have you turned off vibrations in the settings?

**Comment by heberjeur** [comment]
It's the same for me,not working, but it works on yetcalc !

**Comment by heberjeur** [comment]
@Darkempire78 Can you prepare a test version for me to send you the log file?

**Comment by Darkempire78** [comment]
a prioris it's not a bug. your phone is just wrongly set

**Comment by heberjeur** [comment]
I don't think so, also simple calculations is working for me...
