### ISSUE TITLE
Better material you colors 

### ISSUE THREAD

**Issue by HotarunIchijou** [Darkempire78/OpenCalc#244]
Background, symbols and number buttons doesn't match material you colors

Here's a comparison with gcalc

Opencalc
![](https://user-images.githubusercontent.com/113282550/226182381-c730c09d-99db-4fb9-a82b-451edae1820e.png)

Gcalc
![](https://user-images.githubusercontent.com/113282550/226182428-020bf60a-0290-4e32-803d-432d72a54c26.png)

Also it seems like this symbol isn't at the center of the button
![](https://user-images.githubusercontent.com/113282550/226182552-c845be3a-c323-4751-8fa4-f762b16b26a4.png)

**Comment by inson1** [comment]
@Darkempire78 Why dont you close it? Colors are now different. Idk what about the button (but if that is why - why dont  you just open specific issue for the button) ?

**Comment by inson1** [comment]
@Darkempire78 What do you do plan to do with his issue?
