### ISSUE TITLE
Quick Settings Tile

### ISSUE THREAD

**Issue by jarelllama** [Darkempire78/OpenCalc#248]
Hi. I think a quick settings tile would be a nice addition.

The Google calculator app has this feature and it's why I've been sticking to it instead of OpenCalc. I open my calculator very often through the quick settings tile.

Here is a picture of Google Calculator's quick settings tile:
![Screenshot_20230321-185353~2](https://user-images.githubusercontent.com/91372088/226586184-a2bc1911-9a31-4989-a075-01276e990231.jpg)

**Comment by Darkempire78** [comment]
Done
