### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Darkempire78/OpenCalc#249]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/3961260122#L733

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/04395445ad5623d11245c110d0ac9b7045472b5c

**Comment by Darkempire78** [comment]
It should be fixed for then next release

**Comment by Darkempire78** [comment]
@licaon-kter is it fixed ? I do not see the latest version on Fdroid

**Comment by licaon-kter** [comment]
Still in the cogs: https://monitor.f-droid.org

**Comment by TPS** [comment]
It looks this has recurred w/ v3.2.1.  Possible to fix?

**Comment by licaon-kter** [comment]
we already have version 53: https://github.com/clementwzk/OpenCalc/blob/v3.2.1/app/build.gradle.kts#L16

maybe when the next release is ready and the version is bumped

**Comment by TPS** [comment]
I only see v3.2.1 on @IzzySoft's repo, but not F-Droid's.  Based on the dates, F-Droid is behind, build № notwithstanding.

**Comment by licaon-kter** [comment]
Are we lost in translation?

**Comment by TPS** [comment]
> Are we lost in translation?

Maybe?  I only understand v3.2.1, not 53.

**Comment by licaon-kter** [comment]
Each version needs an unique versionCode.

F-Droid picked up 3.2.0 with versionCode 53

Izzy picked up 3.2.1 with versionCode 53.

We can only update to versionCode 54 or higher, in the future, when that is available.
