### ISSUE TITLE
Add engineering notation mode for results

### ISSUE THREAD

**Issue by kenktk** [Darkempire78/OpenCalc#268]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add support for engineering notation of results, I.e. exponents E3, E6, E9, E12, etc.

**Describe alternatives you've considered**
N/A

**Additional context**
None.

**Comment by Darkempire78** [comment]
Already available in the beta https://github.com/Darkempire78/OpenCalc/releases/tag/v3.0.0-beta1
