### ISSUE TITLE
Deleting first digit also deletes following zeroes

### ISSUE THREAD

**Issue by min7-i** [Darkempire78/OpenCalc#275]
**Describe the bug**
When deleting the first digit of a number that starts with a digit [1-9] and is followed by two or more zeroes, e.g. 100, 10.000, etc., the first digit and all zeroes except for the last one are deleted.

For example if I want to replace 100 by 200 I would place the cursor behind the 1 press delete and type 2. Currently this does not work because 1 and 0 are both deleted.

**To Reproduce**
1. Enter a number with at least two zeroes, e.g. 100
2. Place the cursor behind the first digit => 1
3. Press the delete button
4. Not only the 1 but also the 0 following the 1 is deleted

**Expected behavior**
Only the digit after which the cursor is placed should be deleted when pressing the delete button.

**Screenshots/videos**
Here is a screen recording showing the issue:

https://user-images.githubusercontent.com/97251923/233308308-78beeaef-514b-4e12-8cbd-940d872ebbf1.mp4

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6a
 - OS: Android 13.1
 - Version: 2.3.1 and 3.0.0-beta1
 - Language: German

**Additional context**
This also happens with numbers like 100250,23 (where a comma is the decimal separator). When deleting the first digit, the two zeroes are also removed, leaving 250,23 as the remaining digits instead of 00250,23.

**Comment by inson1** [comment]
I think its feature, not bug. And I dont mind this feature. But yea for example Google calculator doesnt have this feature. Maybe it would be bet if there would be option what should happen.

**Comment by Darkempire78** [comment]
> I think its feature, not bug. And I dont mind this feature. But yea for example Google calculator doesnt have this feature. Maybe it would be best if there would be option in settings what should happen. Idk what should be the default option.

You are right, we can add an option for that, it's not a big deal. I think that the Google system is more naturel

**Comment by Darkempire78** [comment]
fixed
