### ISSUE TITLE
App crashes when trying to make the power of a negative number

### ISSUE THREAD

**Issue by Domefemia** [Darkempire78/OpenCalc#289]
**Describe the bug**
The app crashes when try to calculate the power of a number by giving a negative power

**To Reproduce**
1. Click any number
2. Click the "^" button
3. Click the "-" button
4. Click another number

**Expected behavior**
The app to not crash and give an error, or at least give a the result as a fraction
For example 5^-1 = 1/5 so the calc should give 0.2 as a result

**Smartphone (please complete the following information):**
 - Device: Poco X3 NFC
 - OS: LineageOS 20
 - Version 3.0.0-beta2
 - Language Italian

**Comment by Darkempire78** [comment]
Fixed in the v3-beta3
