### ISSUE TITLE
App crashes when trying to calculate the square root of negative number

### ISSUE THREAD

**Issue by Domefemia** [Darkempire78/OpenCalc#290]
**Describe the bug**
The app crashes when try to calculate the square root of negative number

**To Reproduce**
1. Click the "√" button
2. Click the "(" button
3. Click the "-" button
4. Click any number
5. Click the ")" button // if the app doesn't crash first

**Expected behavior**
The app to not crash and give an error "The root of a negative number cannout be calculated"

**Smartphone (please complete the following information):**
 - Device: Poco X3 NFC
 - OS: LineageOS 20
 - Version 3.0.0-beta2
 - Language Italian

**Comment by Darkempire78** [comment]
Fixed in the v3-beta3
