### ISSUE TITLE
Math error when trying to calculate factorial of a negative number

### ISSUE THREAD

**Issue by DomHeadroom** [Darkempire78/OpenCalc#292]
**Describe the bug**
The math make a math error if you try to make the factorial of a negative number, 
by giving as a result the factorial of the number without the minus and then adding the minus to it. 
For example if I do -5! the result given is -120.

**To Reproduce**
1. Click the "-" button
2. Click any number
3. Click the "!" button

**Expected behavior**
The app to give a error like "undefined"

**Smartphone (please complete the following information):**
 - Device: Poco X3 NFC
 - OS: LineageOS 20
 - Version 3.0.0-beta2
 - Language Italian

**Comment by Darkempire78** [comment]
This is not a bug. When you write -5!, it's translated as -(5!), but if you write (-5)! it will give you an error
