### ISSUE TITLE
App crashes when computing a/(b*

### ISSUE THREAD

**Issue by ulrich-mayer** [Darkempire78/OpenCalc#297]
**Describe the bug**
Preview seems to run into a division by zero as long as the first multiplicand is non-integer and second multiplicand is not available and crash.

**To Reproduce**
1. Open app 
2. Type e.g. 2/(3.4*
3. Crash

**Expected behavior**
Either display "Nan" or do not display a result until the second multiplicand is non-zero

**Screenshots/

**Smartphone (please complete the following information):**
 - device Pixel 7
 - Android 13
 - app Version : 3.0.0-beta2
 - Language German

**Additional context**

**Comment by Darkempire78** [comment]
Fixed in the v3-beta3

**Comment by ulrich-mayer** [comment]
Confirm: bug is fixed in version 3.0.0-beta4 from fdroid on 2023-11-07
