### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by vixpr** [Darkempire78/OpenCalc#30]
*Addition to #25*
---
• Instead of 2 options (Theme and Vibration), "Settings" UI would be better. 

• Changing languages within "Settings" UI.

• Changable seperators. (#13, #28)

• Changable button sizes (Big, normal, smaller)

**Comment by Icy-Thought** [comment]
Also, having something similar to Florisboard's theme customization would be nice to have.

**Comment by Darkempire78** [comment]
For the moment we do not need settings panel. 
Separators were added
