### ISSUE TITLE
Crashes when dividing by a number less than 1 and has a zero immediately after the decimal 

### ISSUE THREAD

**Issue by AllenCyborg** [Darkempire78/OpenCalc#300]
**Describe the bug**
OpenCalc version 3.0.0-beta2
The calculator crashes when trying to divide any number with a number <= '0.09', infact it crashes when the zero after the decimal is typed '0.0' without giving me a chance to add the '9'

**To Reproduce**
1. Open the app
2. Type in any number
3. Tap the divide operation
4. Type in any number <= 0.09 as the divisor.

**Expected behavior**
Suppose you are trying to type in 0.09 as the divisor, the app will crash when 0.0 has been entered.

**Screenshots/videos**
https://streamable.com/7hysi3

**Smartphone (please complete the following information):**
 - Device: realme narzo 30a
 - OS: realme ui 2.0
 - Android Version 11
 - Language English

**Comment by Darkempire78** [comment]
Fixed in the v3.0.0-beta3

**Comment by AllenCyborg** [comment]
ok~ thanks
