### ISSUE TITLE
crash: root of negative base

### ISSUE THREAD

**Issue by ulrich-mayer** [Darkempire78/OpenCalc#302]
**Describe the bug**
Type: (-9)^.5 --> app crash

**Expected behavior**
Display either
* Nothing
* Nan
* complex number result
* correct result, e.g. for (-27)^(1/3) = -3

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - OS: Android 13
 - 2023-07-31 f-droid (3.0.0 beta2)
 - Language German

**Comment by ulrich-mayer** [comment]
Looking at you fix that it seems it is incomplete.
Please try (-9)^1.5
I.e I think instead of comparing to less than 1 you should check for integer

**Comment by Darkempire78** [comment]
you are right lmao

**Comment by ulrich-mayer** [comment]
Confirm: bug is fixed in version 3.0.0-beta4 from fdroid on 2023-11-07
