### ISSUE TITLE
App crash when doing log or ln of a negative number

### ISSUE THREAD

**Issue by Domefemia** [Darkempire78/OpenCalc#316]
**To Reproduce**
1. Click on 'ln' or 'log'
2. Click on '-'
3. Click on any number

**Expected behavior**
To give you the same error as log(0)

**Smartphone:**
 - Device: PocoX3 NFC 
 - OS: Android 13
 - Version: 3.0.0-beta2
 - Language: Italian

**Comment by TauAdam** [comment]
The same error

**Comment by inson1** [comment]
I think I cant reproduce it.
Ofc if you dont talk about "Math error" message and I think you dont ![Screenshot_2023-10-24-11-04-13-066_com.darkempire78.opencalculator.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/ee2c5bb3-8204-4e41-8ec1-8b94c373196a)

![Screenshot_2023-10-24-11-01-52-484_com.darkempire78.opencalculator.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/f68f7096-850c-4da1-86e8-ce6b19306c66)

![Screenshot_2023-10-24-11-01-15-574_com.darkempire78.opencalculator.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/37608c83-dd72-42f2-a714-d4d3964ec3f9)

**Comment by Domefemia** [comment]
Because probably now is fixxed

**Comment by inson1** [comment]
@Domefemia It would be closed + there isnt any new release.

**Comment by Domefemia** [comment]
What app version are you using?

**Comment by Domefemia** [comment]
And the report is done on 3.0.0-beta2

**Comment by inson1** [comment]
@Domefemia Oh ... Sorry. I didnt realize you were on beta release

**Comment by inson1** [comment]
In latest beta version I can reproduce it.

**Comment by Darkempire78** [comment]
fixed
