### ISSUE TITLE
Show Changelog after clicking on version in About page 

### ISSUE THREAD

**Issue by inson1** [Darkempire78/OpenCalc#322]
I meant current and past versions with changes and dates of releases

And thanks message could be moved to "Made with ❤️ in France"

**Comment by Darkempire78** [comment]
Idk if it's very usefull and there is several bugs to fix before. I'm not sure to implement that. But, you can make a pull request to add it

**Comment by inson1** [comment]
@Darkempire78 yea this isn high priority issue. I have to do some work else where before that. I would imagine that like tags/releases on Github.

**Comment by inson1** [comment]
@Darkempire78 Would you ming having there alls realease or would you only want the last one?

**Comment by Darkempire78** [comment]
> @Darkempire78 Would you ming having there alls realease or would you only want the last one?

I thing that it sould show the latest and if you click on a button like "see previous updates" it should show every changelog, what do you think ?

**Comment by inson1** [comment]
@Darkempire78 That was more question about size of data and application. Now there 40 releases, but the app isnt very old

So on first page show only last release and then show page with list of expansion items? 
Btw I think it would be better to add even last release on next page. It should be complete history. But I agree, in most cases user would care only about the last release changelog

**Comment by Darkempire78** [comment]
@inson1 You are right, the app is small and ading 40+ release will increase the size a lot "for nothing". Let's keep only the latest update

**Comment by inson1** [comment]
@Darkempire78 What about at least adding x last releases, so even if the app doesnt get few weeks/months updated, user can still see all updates between his old version and the new one? Lets say 5? 10?

Or is that bad idea?

**Comment by Darkempire78** [comment]
> @Darkempire78 What about at least adding x last releases, so even if the app doesnt get few weeks/months updated, user can still see all updates between his old version and the new one? Lets say 5? 10?
> 
> Or is that bad idea?

Yes we can do that, I think that 5 releases is enough. I wonder if it is possible to automate the addition of the last 5 releases without having to put them in manually each time

**Comment by inson1** [comment]
@Darkempire78 
Maybe it could be done with github actions, but it would be harder and more time consuming than building the whole changelog itself
But that problem would be even with the last release - you would delete one, add one - it would be the same 

I also now realized, that the last release would be without translations.
