### ISSUE TITLE
F-Droid clarification of information

### ISSUE THREAD

**Issue by inson1** [Darkempire78/OpenCalc#324]
App no longer takes up 2 MB

![Screenshot_2023-10-13-18-54-55-988_org.fdroid.fdroid.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/741bc4d8-fc0a-4723-a3b9-03c1f98f7a84)

**Comment by Darkempire78** [comment]
the latest apk takes 1.77mb

**Comment by inson1** [comment]
Oh ok. You meant APK. Because the app takes more than that. 
Maybe add APK to the text, so nobody thinks that the app should take only 2 MB?
"(APK ~2MB)"
![Screenshot_2023-10-13-19-16-47-578_com.android.settings.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/0414881c-fbb7-4b74-9c19-464a5b6797b4)

**Comment by Darkempire78** [comment]
The size of the app depends of your phone. On mine, it takes 4mo

**Comment by inson1** [comment]
@Darkempire78 Interesting. I didnt know that. Do you know why? And do you agree with clarification of the information?

**Comment by Darkempire78** [comment]
> @Darkempire78 Interesting. I didnt know that. Do you know why? And do you agree with clarification of the information?

https://www.quora.com/Same-app-occupied-different-space-in-different-companys-smart-phone-where-Android-version-are-same-in-both-phone-so-what-is-the-reason-behind-that

**Comment by inson1** [comment]
@Darkempire78 And What about the clarification?

**Comment by Darkempire78** [comment]
@inson1 yes it could be a good idea, can you open a pull request for that please ?

**Comment by Darkempire78** [comment]
done
