### ISSUE TITLE
[BETA-BUG] Result - text color + background color

### ISSUE THREAD

**Issue by inson1** [Darkempire78/OpenCalc#327]
**Screenshots/videos**
![Screenshot_2023-10-24-12-38-51-665_com.darkempire78.opencalculator.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/5d1247c3-c312-45cf-b502-a922bcaa0188)

![Screenshot_2023-10-24-12-22-08-127_com.darkempire78.opencalculator.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/47a8d2b4-2633-407c-9b2e-762ae2a98d97)

Btw System theme is Dark theme
![Screenshot_2023-10-24-12-22-17-387_com.darkempire78.opencalculator.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/b724738e-76e2-46c4-ad5d-33c3ccd5d21e)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi note 8 Pro
 - OS: Android 11 MIUI 12.5.7
 - Version: 3.0.0 beta 2
 - Language:  English

**Comment by Darkempire78** [comment]
Do you force the dark mode on your mobile phone ? I know that this Xiaomi's option is very terrible

**Comment by inson1** [comment]
@Darkempire78 Its set as system/defaul option. Btw it worked in last version. Only the beta has his bug.

**Comment by Darkempire78** [comment]
That's very weird, I'm not able to reproduce it

**Comment by inson1** [comment]
@Darkempire78 I will wait for next release of the beta and try it again

Did you try emulator with my phone? Or another Xiaomi phone? (I hope you can emalate  Android studio Xiaomi phones)

**Comment by inson1** [comment]
@Darkempire78 Ok, I tried new beta, I can still see the bug. It can be seen right after opening the app.

**Comment by Darkempire78** [comment]
> @Darkempire78 Ok, I tried new beta, I can still see the bug. It can be seen right after opening the app.

but the "THEME" bug was solved at least ?

**Comment by inson1** [comment]
@Darkempire78 Yes that work. But Its different issue. Third problem is solved partly. I write about them in their issues
