### ISSUE TITLE
Why are on F-Droid only 2 beta versions and not all 3? And Why have same name?

### ISSUE THREAD

**Issue by inson1** [Darkempire78/OpenCalc#328]
![Screenshot_2023-10-24-12-46-59-799_org.fdroid.fdroid.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/f175fd8d-4fd5-46f3-a5ff-f8911c0456c7)

**Comment by Darkempire78** [comment]
No idea to be honest

**Comment by inson1** [comment]
@Darkempire78 It is automatic, right? Maybe I should open issue on F-Droid?

**Comment by Darkempire78** [comment]
> @Darkempire78 It is automatic, right? Maybe I should open issue on F-Droid?

Yes it is, but perhaps I made a mistake no idea lol

**Comment by inson1** [comment]
Okay lets see 3. beta version
