### ISSUE TITLE
Crash when operator added to left side of thousands separators

### ISSUE THREAD

**Issue by mwadle** [Darkempire78/OpenCalc#329]
**Describe the bug**

Given a number with a thousands 

Given certain numbers with a thousands separator, inserting an operator in between two numbers to the left of the leftmost thousands operator will cause a crash.

I have only consistently been able to recreate this in situations where both:
1. the first number after the thousands separator is a 0
2. The two numbers directly to the right of the inserted operator are zero

See the last example in additional context for a situation where both these rules apply, but a crash still does not happen.

**To Reproduce**
1. Enter the number 10,000
4. Place the cursor between the 1 and 0 to the left of the thousands separator
5. Enter an addition sign
6. Observe crash

**Expected behavior**
App does not crash

**Screenshots/videos**
If applicable, add screenshots or videos to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord N20 5G
 - OS: Android 12
 - Version: 3.0.0-beta2 and 3.0.0-beta4
 - Language: English

**Additional context**
There are situations where behavior seems to be inconsistent. For examples:

11,000 -> 11+000 = no crash
11,000,000 -> 11+000,000 = crash

100,000 -> 10+0,000 = crash
100,010 -> 10+0,010 = no crash

**Comment by mwadle** [comment]
I believe this is caused by the same code underlying issue #218. In updateDisplay, there is currently a cursor offset that is added to the cursor display. This offset is found by subtracting newValueFormatted.length - newValue.length. In cases where the formatted value is less than the unformatted value this value will be negative.

I believe the cause of the crash is cursorOffset being negative, which can cause the desired cursor position to be less than 0 which crashes the app. I am currently working on a fix for #218 which would also fix this.

**Comment by Darkempire78** [comment]
Fixed
