### ISSUE TITLE
Weblate - Maximum length of translation

### ISSUE THREAD

**Issue by inson1** [Darkempire78/OpenCalc#331]
Is there way to solve this? 
Btw the string isnt fully translated yet, but I dont think that it will be smaller
![image](https://github.com/Darkempire78/OpenCalc/assets/75314629/9f4a17a2-95ab-4a93-ac22-b721a92e6af9)

**Comment by Darkempire78** [comment]
I do not understand how to change that, btw the default length is 10 times the default string, what is the string that you want to translate ?

**Comment by inson1** [comment]
@Darkempire78 I'm not the only one.
![image](https://github.com/Darkempire78/OpenCalc/assets/75314629/3c91658c-3989-4819-97c2-31074952e65a)

**Comment by inson1** [comment]
Ok its weblate feature https://github.com/WeblateOrg/weblate/issues/1525#issuecomment-462402371

**Comment by inson1** [comment]
@Darkempire78 
What about to shorten the translations to something like "translations of new languages"? So the translations wont be cut.
What about 30% of new texts let for translations? So there is enough characters left.

https://ititranslates.com/blog/size-matters-text-length-when-translating-from-english
https://www.star-ts.com/translation-faq/why-is-the-length-of-a-translation-important
https://www.atltranslate.com/articles/prepare-for-software-localization
https://www.andiamo.co.uk/resources/expansion-and-contraction-factors/

Google + F-Droid
Title/Name 30-50 (Google play vs f-droid) (21)
Short Description/Summary 80 (56)
Full Description/Description 4000 (2800)
Changelog 500 (350)

https://dgtlmart.com/blog/google-changed-character-limit-for-app-title-in-google-play-store/
https://f-droid.org/en/docs/Build_Metadata_Reference
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

**Comment by inson1** [comment]
This string is also too long for some languages 
![brave_UmBj6su12m](https://github.com/Darkempire78/OpenCalc/assets/75314629/446f138e-bbbe-40a2-9359-62acbac67082)

**Comment by Darkempire78** [comment]
changelogs are not vert important but yes it would ne cool to dix that

**Comment by inson1** [comment]
@Darkempire78 well, no but, part of hard worked translations from people are being cut off

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
