### ISSUE TITLE
Everything after ').' in a calculation is ignored

### ISSUE THREAD

**Issue by mwadle** [Darkempire78/OpenCalc#340]
**Describe the bug**
Whenever a closed parenthesis is followed by a decimal, any text after the decimal is ignored

**To Reproduce**
1. Enter open parenthesis, then the number five, then close parenthesis "(5)"
2. Enter a decimal "(5)."
3. Observe how anything you enter after the decimal is ignored when calculating the result "(5).1234+64x9" equals 5

**Expected behavior**
The entire entered expression is included when calculating the result

**Screenshots/videos**
If applicable, add screenshots or videos to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord N20 5G
 - OS: Android 12
 - Version: 3.0.0-beta4
 - Language: English

**Additional context**

**Comment by Darkempire78** [comment]
For the moment it return an expression error, but it will be added with the #349
