### ISSUE TITLE
Cursor jumps when deleting a decimal with a leading zero

### ISSUE THREAD

**Issue by mwadle** [Darkempire78/OpenCalc#342]
**Describe the bug**
The cursor jumps to the right one spot when deleting a decimal with a leading zero

**To Reproduce**
1. Enter "0.12"
2. Place cursor to the right of the decimal and press backspace button
3. Observe cursor jumping between the 1 and the 2 after decimal is deleted

**Expected behavior**
Cursor remains to the left of the 1 digit

**Screenshots/videos**
If applicable, add screenshots or videos to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord N20 5G
 - OS: Android 12
 - Version 3.0.0-beta4
 - Language English

**Additional context**

**Comment by Darkempire78** [comment]
fixed
