### ISSUE TITLE
Maybe wrong word order in the sentence?

### ISSUE THREAD

**Issue by inson1** [Darkempire78/OpenCalc#345]
My english isnt perfect, so maybe i'm wrong. But shouldnt: 
 "For major changes, please open an issue first to discuss what you would like to change."
be: 
"For major changes, please open an issue first to discuss what would you like to change." ?

**Comment by Darkempire78** [comment]
idk, we needs a native english user to know lmao

**Comment by inson1** [comment]
@Darkempire78 yea, lets wait for native english speeker

**Comment by mwadle** [comment]
As a native English speaker, keep the original ("you would").

As an aside, I didn't know why the current wording is better other than just that it "sounded" better to me, so I turned to chatGPT for an explanation:

![Screenshot_2023-11-05-12-37-37-69](https://github.com/Darkempire78/OpenCalc/assets/34467087/040926fe-30b2-4704-a8a0-c2b26ec1b557)

**Comment by Darkempire78** [comment]
thanks!

**Comment by inson1** [comment]
Ok, sorry, it sounded wierd, I had to ask

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
