### ISSUE TITLE
100-10% = 99,9 instead of 90

### ISSUE THREAD

**Issue by Bolsderac** [Darkempire78/OpenCalc#35]
Hi,
Bad result with % operator.
for exemple : 100-10% = 99,9 instead of 90.
See attachment.
Arnaud 
![Screenshot_20220812-225853](https://user-images.githubusercontent.com/60016981/184444377-4760c297-d9d4-4cb4-bca1-490f4f759cfb.jpg)

**Comment by bonswouar** [comment]
Yeah I think what you wanted to do is `100*90%` or `100-(10%*100)`

**Comment by Bolsderac** [comment]
No, most of calculators don't need such mathematic syntax. Only 100-10%. Try for exemple with Google or Oneplus calculator. I'm sure.

**Comment by Bolsderac** [comment]
No, most of calculators don't need such mathematic syntax. Only 100-10%. Try for exemple with Google or Oneplus calculator. I'm sure (see attachment)
![Screenshot_20220813-171530](https://user-images.githubusercontent.com/60016981/184500339-f3347d0b-0a36-4027-94bd-6644ac5c2e63.jpg)

**Comment by bonswouar** [comment]
@Bolsderac Looks like your right, even AOSP calculator, I'm surprised I've never noticed!
I guess that's not very mathematical but if you want to be very mathematical you wouldn't use the % sign...

So apparently the rule seems to be: when there is `Y+/- X%` it's calculated as `Y +/- ((Y))*X/100)`, and Y can be anything

**Comment by Darkempire78** [comment]
Fixed 589276eb33172a74faf88d91007a026b7ffa6e08
