### ISSUE TITLE
[BUG] Light theme doesnt work

### ISSUE THREAD

**Issue by inson1** [Darkempire78/OpenCalc#352]
Like this
![Screenshot_2023-11-05-22-39-46-652_com.google.android.calculator.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/518af6df-5106-4226-b6fe-220b845e3aa4)

**Comment by Darkempire78** [comment]
what is the différence with the light theme of OpenCalc ?
![Screenshot_20231105-224411](https://github.com/Darkempire78/OpenCalc/assets/50015928/10e39f77-e94d-4596-9590-cd67a17bf5b4)

**Comment by inson1** [comment]
@Darkempire78 ok, interesting
I thought this was the Light theme 
![Screenshot_2023-11-05-22-45-31-455_com.darkempire78.opencalculator.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/a5594311-7672-4012-9b00-ade5290aaf6e)

I will change the title

**Comment by inson1** [comment]
Device: Xiaomi Redmi note 8 Pro
OS: Android 11 MIUI 12.5.7
Version: 3.0.0 beta 4
Language: English

**Comment by Darkempire78** [comment]
I hate Xiami devices lol

**Comment by inson1** [comment]
@Darkempire78 And can you emulate them in Android studio?
