### ISSUE TITLE
F-Droid - Do not suggest beta versions

### ISSUE THREAD

**Issue by inson1** [Darkempire78/OpenCalc#358]
Please suggest only stable versions.

+ Beta versions arent even set as betas

**Comment by Darkempire78** [comment]
idk how to set beta version as beta on fdroid x)

**Comment by inson1** [comment]
Okay good news, decription is updated automatically, so we only need to find how to set the beta version

**Comment by Darkempire78** [comment]
We should ask on their forum

**Comment by inson1** [comment]
@Darkempire78 I already did - https://forum.f-droid.org/t/how-to-set-release-on-github-that-is-automatically-updated-to-f-droid-as-beta-and-stable/24121

It cant be done by automatically. Maybe one day
It can be done only manually via a merge request.

I dont how much time it can take. But it would be great not suggesting software in beta. 
If it is same as here. It can take max few minutes each. So maybe we could to set beta versions even from 2.0.

There are 3 flags unstable/beta/alpha (+1 stable). Idk how they work, I will do more research. Idk if we should set only beta or  unstable + beta.

**Comment by Darkempire78** [comment]
😴
