### ISSUE TITLE
"Fix:" vs "Fixed:" vs "Fixes:" in changelogs

### ISSUE THREAD

**Issue by inson1** [Darkempire78/OpenCalc#362]
We should choose only one and use it (ofc if there isnt any another reason for it) (or 2 - fixes, fix - if there is 1 or more changes)

I will create PR, but before that we should discuss what version we should choose

**Comment by inson1** [comment]
Maybe "Fixed:" so its same time as "Updated:" 
(but in that case we should also change "Change:")

**Comment by Darkempire78** [comment]
I use "fixes" since the v3 beta, it seems good 
![image](https://github.com/Darkempire78/OpenCalc/assets/50015928/77c4f1cf-a3ee-4127-97c8-32d2ff175bc2)

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
