### ISSUE TITLE
Translating to persian!

### ISSUE THREAD

**Issue by nimafanniasl** [Darkempire78/OpenCalc#40]
Hey, I found your good app and added it to Persian Free software alt's repo: https://github.com/nimafanniasl/FreeSoftwareAlts/blob/main/Android.md#%D9%85%D8%A7%D8%B4%DB%8C%D9%86-%D8%AD%D8%B3%D8%A7%D8%A8
and because of that, I want to translate this app to Persian :)
Where is the .po file? thanks!

**Comment by Darkempire78** [comment]
You have to create a folder here (https://github.com/Darkempire78/OpenCalc/tree/main/app/src/main/res) named "values-YOURLANGUAGE" (e.g for english : "values-en").
Then create a file named "strings.xml" with this content : 
````Xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name_display">Calculator</string>
    <string name="select_theme_title">Select a theme</string>
    <string name="app_menu_theme">Theme</string>
    <string name="app_menu_vibration">Vibration</string>
    <string name="app_menu_about">About</string>
</resources>
```
Thanslate each value and make a pull request!

**Comment by nimafanniasl** [comment]
Thanks!
