### ISSUE TITLE
Landscape mode hides some button icons

### ISSUE THREAD

**Issue by drrnb** [Darkempire78/OpenCalc#402]
**Describe the bug**

**To Reproduce**
1. Put the phone in landscape mode / rotate phone to landscape mode
2. Some button icons disappear

**Expected behavior**
Button icons to stay no matter the orientation

**Screenshots/videos**
![image](https://github.com/Darkempire78/OpenCalc/assets/92945277/6b256183-7c71-41a8-a6fb-c2b6a842d6c6)

**Smartphone (please complete the following information):**
 - Device: Nothing Phone 2
 - OS: Nothing OS 2.5.1.A / Android 14
 - Version: Android 14
 - Language: English (GB)

**Comment by Darkempire78** [comment]
What is your version of Opencalc ?

**Comment by drrnb** [comment]
Latest from F-Droid (or this repo, does the same)
`3.0.0-beta4`

**Comment by Darkempire78** [comment]
You are right lol, it's a new bug due to a refactor in thé latest version I think, I will fix that today
