### ISSUE TITLE
Comma seperator not working inside parenthesis

### ISSUE THREAD

**Issue by Heikrana** [Darkempire78/OpenCalc#403]
**Describe the bug**
Comma at every thousandth place not coming inside parenthesis but only 1 comma no matter how many zeros. This happens when you add a lot of parenthesis.

**To Reproduce**
1. Do some calculation with parenthesis and inside as well.
2. After certain number of parenthesis comma seperator will malfunction.

**Expected behavior**
Comma seperator should work properly.

**Screenshots/videos**
![Screenshot_20240112_202404_Calculator](https://github.com/Darkempire78/OpenCalc/assets/49754221/883be355-372c-4bcb-a453-485e3712b76b)

**Smartphone:**
 - Device: Samsung Galaxy S21 FE
 - OS: Android 14
 - App version: v2.3.1 (apk from GitHub)
 - Language: English

**Additional context**
It might be related to locality as in Indian number system, 1st comma seperator comes at 1000th place and then at every 100th place.

**Comment by muryno** [comment]
PR fix is raised for this,

**Comment by Darkempire78** [comment]
fixed
