### ISSUE TITLE
Option for fixed orientation

### ISSUE THREAD

**Issue by opk12** [Darkempire78/OpenCalc#413]
**Is your feature request related to a problem? Please describe.**
Auto-rotate sometimes triggers when I put the phone on the table and pick it up, because it is covered with documents. This creates an unpleasant effect, and I prefer using the portrait mode for the calculator.

**Describe the solution you'd like**
Is it possible to have an option to fix the orientation to Portrait?

**Describe alternatives you've considered**
I want to keep Auto-rotate enabled, as I use most apps with the phone in the hand.

**Comment by inson1** [comment]
so option to choose fixed orientation in settings with these 3 options - System, Portrait, Landscape and System would be set by default

**Comment by subhajit-rajak** [comment]
@Darkempire78  I'm on it

**Comment by subhajit-rajak** [comment]
Hi!👋 @Darkempire78 I have opened a pr for this issue [Check here](https://github.com/Darkempire78/OpenCalc/pull/488)

**Comment by TanishMoral11** [comment]
@Darkempire78 I'm on it

**Comment by Darkempire78** [comment]
You are right @TanishMoral11 , thanks
