### ISSUE TITLE
[BUG] Gray rectangle next to Settings

### ISSUE THREAD

**Issue by inson1** [Darkempire78/OpenCalc#420]
**To Reproduce**
Sometimes it appears after changing theme

**Expected behavior**
No gray rectangle

**Screenshots/videos**
<div>
<img src="https://github.com/Darkempire78/OpenCalc/assets/75314629/2a499581-48c7-47a8-8c07-f0ccac57d57b" height="400">
<img src="https://github.com/Darkempire78/OpenCalc/assets/75314629/f9cfb6db-6353-4027-b31a-1c902a4b3747" height="400">
</div>

**Smartphone (please complete the following information):**
I could repro on 2 devices - Xiaomi and Samsung

Xiaomi
 - Device: Redmi note 8 pro
 - OS: Android 11
 - App version v3.0.0-beta4

Samsung
- Device: GALAXY J6
- OS: Android 10
- App version v3.0.0-beta4

**Comment by inson1** [comment]
@Darkempire78 It could be cursor yes, but idk why it appears only sometimes

**Comment by inson1** [comment]
Okay on Amoled its too

**Comment by inson1** [comment]
Light->Dark = yes
Light->Amoled = yes

Dark->Light = yes
Dark->Amoled = no

Amoled->Light = yes
Amoled->Dark = no

**Comment by Darkempire78** [comment]
I think it's when the app change to light to dark mode (not the case when you do dark->amoled or amoled->dark)

**Comment by inson1** [comment]
@Darkempire78 read my comment, there are all cases

**Comment by inson1** [comment]
yes I write all cases
