### ISSUE TITLE
function tan-1 out of domain issue

### ISSUE THREAD

**Issue by camzilla1050** [Darkempire78/OpenCalc#428]
** **
There is an issue using "tan-1" function, if alpha is > 1 then return out of domain

Example:

![Screenshot_20240210-155629](https://github.com/Darkempire78/OpenCalc/assets/10384623/a53da2ef-edf3-4c5d-9a40-63a21fc4c225)

 Works if <=1
![Screenshot_20240210-155647](https://github.com/Darkempire78/OpenCalc/assets/10384623/b649a19e-14fd-4f33-beb7-8e710ae75264)

**Comment by muryno** [comment]
@camzilla1050  tested this and it worked fine for me, maybe you have older version

<img width="336" alt="Screenshot 2024-02-16 at 15 23 57" src="https://github.com/Darkempire78/OpenCalc/assets/26343440/ca54acfe-9bd7-4ff6-9f86-d715c6bd5f9d">

**Comment by inson1** [comment]
It works for me too (I mean the right way) (newest F-droid version)
@camzilla1050 @muryno What version did you used? Debug? F-droid? Google play

**Comment by muryno** [comment]
@inson1  I tested on debug

**Comment by inson1** [comment]
yea, I hope for that, so we would know about debug too

@Darkempire78 May you close it? as this works
