### ISSUE TITLE
In horizontal rotation basic calculations buttons not show lables on them like 

### ISSUE THREAD

**Issue by nhitachi1994** [Darkempire78/OpenCalc#435]
![Screenshot_2024-03-12-10-40-44-44_7b7a71e2662e0d1cbba227111d207c2e](https://github.com/Darkempire78/OpenCalc/assets/163094877/da3d9e1b-54a6-4a5f-a168-6ec6aaf2ed56)
 In horizontal rotation basic calculations buttons not show lables on them.

**Comment by Darkempire78** [comment]
fixed, wait the release
