### ISSUE TITLE
Four zeros after comma

### ISSUE THREAD

**Issue by elgidiom** [Darkempire78/OpenCalc#450]
In certain calculations you can obtain a number like 150,0000 what is incorect notation

**To Reproduce**

1. Sum 5000 + 500000
In the screen you would see:
5,000+5,00000

**Expected 
see: 5,000+ 500,000

**Screenshots/videos**
![Screenshot_20240427_222424_Calculator](https://github.com/Darkempire78/OpenCalc/assets/159052818/da845405-b620-42e2-adfc-8adec8f5bf0e)

**Smartphone (please complete the following information):**
 - Device: [galaxy A14]
 - OS: [android]
 - App version 3.0.0
 - Language spanish

**Comment by jerryn70** [comment]
I think displaying 5,00,000 is much better than 500,000

**Comment by MahmoudRH** [comment]
@Darkempire78 is there anybody working on this issue?

**Comment by Darkempire78** [comment]
not for the moment @MahmoudRH

**Comment by MahmoudRH** [comment]
You can assignt it to me, i am gonna work on this issue.

**Comment by MahmoudRH** [comment]
the issue occurs whenever the number is repeated somehow in the same expression.
ex: 
4000 + 40000
result: 4,000 + 4,0000
