### ISSUE TITLE
Please, add to the OpenCalc minSDK_21 (Android_5.0) !

### ISSUE THREAD

**Issue by DI555** [Darkempire78/OpenCalc#453]
If possible, please, add to the OpenCalc minSDK_21 (Android_5.0)!
Or, at least, minSDK_22 (Android_5.1) !

We all still have many devices with Androids 5+ , and will be great to use OpenCalc there!
Many thanks in advance!

**Comment by Darkempire78** [comment]
Android v5 represents less than 2% of users. I'm not sure it will be worth to support them... i do not have the time for that, but if someone wants to contribute it possible for sure

**Comment by Darkempire78** [comment]
done
