### ISSUE TITLE
crash when pressing square root after Syntax error

### ISSUE THREAD

**Issue by GuitarBilly** [Darkempire78/OpenCalc#455]
hello, and thanks for this beautiful calculator.

**Describe the bug**
When i tried to use it as my real calculator the app crashed.
If you use the square root wrongly it first mentions Syntaxfout (Syntax error). When pressing square root once after that the app always crashes hard.

**To Reproduce**
1. press any number (optional)
2. press square root
3. press =
4. notice **Syntaxfout** (**Syntaxerror**) shows up in the screen. >>> first screenshot
5. press square root
6. the app crashes hard. >>> second screenshot

**Expected behavior**
The app can show an error message or inform the user, but it should not crash hard on an incorrect sequence of input.

**Screenshots/videos**
![Screenshot_20240520-192027](https://github.com/Darkempire78/OpenCalc/assets/38086529/28e4bf5e-1549-4c31-9eee-335e9f3a5b57)
![Screenshot_20240520-192035 blr](https://github.com/Darkempire78/OpenCalc/assets/38086529/548fb57a-52bb-484d-913f-b4847a0e2064)

**Smartphone (please complete the following information):**
- Model = Nokia 6 - TA-1033
 - OS = Android 7.1.2
 - App version = 3.0.0
 - Language = Dutch 

**Additional context**
none.

**Comment by ikanakova** [comment]
On Samsung Galaxy A53, Android 14, version 3.0.0 from F-Droid works as it should - it writes a syntax error, but does not crash.

**Comment by Darkempire78** [comment]
> On Samsung Galaxy A53, Android 14, version 3.0.0 from F-Droid, czech localization works as it should - it writes a syntax error, but does not crash.

Same for me on my Pixel 6
