### ISSUE TITLE
Option to clear history

### ISSUE THREAD

**Issue by Ziys35** [Darkempire78/OpenCalc#46]
The option to clear history would be very useful. It would be great if you add the feature. Thank you

**Comment by Darkempire78** [comment]
Where do you think I should add the button to clear the history in the UI ? @Ziys35

**Comment by Ziys35** [comment]
The 3 dot menu should be fine

**Comment by Darkempire78** [comment]
Done cc71a8c4546db851549b81d0b35fc7685c6cfe75
