### ISSUE TITLE
Automated history by typing

### ISSUE THREAD

**Issue by szemydavis21** [Darkempire78/OpenCalc#466]
I had on my old phone(oneplus)the System calculator that had this feature,when I type the Numbers and this was listed to the history whitout hitting the =.
This was for me wunderful,and I cant find an otherone with the same solution.

**Comment by Darkempire78** [comment]
I added that option in a new branch https://github.com/Darkempire78/OpenCalc/tree/fix-%23466, I will test it to be sure there is no bug. Then I will publish it
