### ISSUE TITLE
History scroll optimization

### ISSUE THREAD

**Issue by Ziys35** [Darkempire78/OpenCalc#47]
1. https://user-images.githubusercontent.com/111631941/185736414-e5db0271-b0c3-4278-b123-65ab8b32eb3f.mp4

In the above video you can see that the calculation before the (1+3) is cannot show , the app only shows the recent 6 calculation.It needed to be fix. Thank you.

2. And one more request theposition of the history section and current expression section should be vice versa.It helping a lot for much easier opening the history section.

**Comment by MahmoudRH** [comment]
@Darkempire78 Check my pull requests

**Comment by Darkempire78** [comment]
It should be fixed now

**Comment by Darkempire78** [comment]
Not yet fully fixed

**Comment by Darkempire78** [comment]
Fixed in the v2.0.0-beta2
