### ISSUE TITLE
Add double/triple zero button

### ISSUE THREAD

**Issue by afterdark1880** [Darkempire78/OpenCalc#470]
Default calculator on my phone includes a double zero button, which comes handy when operating with hundreds and thousands. 

![IMG_20240623_090556](https://github.com/Darkempire78/OpenCalc/assets/149618471/95e92de1-293c-4780-93ce-4779422b7e1f)

That could be a nice addition to your calculator. 
If this means rearranging the whole keyboard layout, you might as well activate an option that let the user choose whether to enter a double or triple zero simply by long-pressing the zero button.

Thank you for considering this.

**Comment by subhajit-rajak** [comment]
Can I work on it?

**Comment by subhajit-rajak** [comment]
![Screenshot_20240711_231552_Calculator.png](https://github.com/Darkempire78/OpenCalc/assets/91543367/a4776065-b8fe-49fa-87de-6360b964a850)

I made it like this. It works perfectly. What do you think @afterdark1880 @Darkempire78

**Comment by Darkempire78** [comment]
@subhajit-rajak To be honest the layout looks very weird. Perhaps that other calculators have better layout with 00 and 000

**Comment by subhajit-rajak** [comment]
@Darkempire78  I agree, the Oneplus devices have double zero button but they do not have the parenthesis button in the main tab. It could be included in the scientific mode. What do you think?

**Comment by afterdark1880** [comment]
> I made it like this. It works perfectly. What do you think @afterdark1880 @Darkempire78

@subhajit-rajak Thank you for your contribution. It does look a bit weird. Maybe it's a matter of replacing instead of adding buttons, isn't it? Or, as I suggested first, a long press on the 0 button could show double and triple-0 options.

**Comment by Darkempire78** [comment]
I agree, long press seems to be a good way to implement that

**Comment by subhajit-rajak** [comment]
@Darkempire78 @afterdark1880 I'm on it

**Comment by subhajit-rajak** [comment]
Hi!👋 @Darkempire78 I have opened a pull request for this issue [check here](https://github.com/Darkempire78/OpenCalc/pull/485)

**Comment by Darkempire78** [comment]
Done
