### ISSUE TITLE
Use Unicode minus for minus key

### ISSUE THREAD

**Issue by StevanWhite** [Darkempire78/OpenCalc#49]
Hi,

Nice calculator!

I notice one thing immediately: on the minus key, you are using ASCII 'hyphen', U+002D.
It would be much better to use the proper typographic minus: U+2212.
In most fonts, that glyph is designed to look like the plus, times, divide, and equals, whereas 'hyphen' is a word-divider.

Cheers!

**Comment by Darkempire78** [comment]
Done 407cd8028a67e61951eb751d8253529507e822db
