### ISSUE TITLE
Improve Buttons Shape

### ISSUE THREAD

**Issue by PassionateG1t** [Darkempire78/OpenCalc#52]
Right now, on my phone (6.24 x 2.90 INCH) the buttons are elongated and look more like ovals than actual circles. It could be just me, so I understand if you're not looking to do anything about it. Thank you.

![Screenshot_20220821-214145_Calculator](https://user-images.githubusercontent.com/107609269/185806166-006a92a8-a795-4a50-88f8-1832b812b030.jpg)

**Comment by Darkempire78** [comment]
The size of the buttons changes depending on the height of the phone, they will be flattened on a less tall phone and slightly oval on a very tall phone.
