### ISSUE TITLE
Add logo to arcticons

### ISSUE THREAD

**Issue by inigochoa** [Darkempire78/OpenCalc#53]
Hey! Love the app and love your work! I wish I had the knowledge to do the things you do.

I use Arcticons as my main icon-pack. It would be great if you could include the logo inside the articons. The developer has a [contributing guide](https://github.com/Donnnno/Arcticons/blob/main/CONTRIBUTING.md) with the few steps needed.

**Comment by candroid-man** [comment]
Honestly, just use the default Google calculator icon. If you can't choose different icons per app consider using a launcher that supports it such as Neo Launcher (FOSS)

**Comment by Darkempire78** [comment]
To be honest I've been trying a bit to do the logo for Articons, but I don't know what software to use. From what I tested it was complicated and not intuitive... 
I suggest you either to redo the logo yourself for me, or to suggest me a simple software to use @inigochoa @candroid-man

**Comment by inigochoa** [comment]
Sorry! Forgot to say that they added the icon in the last update. The commit is [90712c3](https://github.com/Donnnno/Arcticons/commit/90712c305cf7e0605e51d80ee4a5546e10aa7a27) and [the file](https://github.com/Donnnno/Arcticons/blob/6a10d65c03e0a2660e044321062bb37bd1d971ef/app/src/dark/res/drawable-nodpi/opencalc.png). Hope it looks good to you

**Comment by Darkempire78** [comment]
Oh cool thanks!
