### ISSUE TITLE
keyboard size settings

### ISSUE THREAD

**Issue by OmlineEditor** [Darkempire78/OpenCalc#57]
the size of the keyboard is best adjusted in height so that it is convenient to work with one hand on a large screen.

make settings for keyboard height

**Comment by OmlineEditor** [comment]
why did you close the ticket? I offer you an idea to improve the functionality and convenience

**Comment by Darkempire78** [comment]
Now that I have enabled discussions on GitHub you can propose your improvement in a post in the discussions to discuss it with other users!
