### ISSUE TITLE
transferring long text to another line

### ISSUE THREAD

**Issue by OmlineEditor** [Darkempire78/OpenCalc#58]
when you enter a long expression to calculate, the text goes off the edge of the screen. it's inconvenient. you need to move the text to another line so that the entire expression fits on the screen. the number of troks needs to be built up. the user himself will choose how many lines he needs at most (from 3 to 10 lines)

**Comment by Darkempire78** [comment]
You can also scroll to see the whole expression

**Comment by OmlineEditor** [comment]
why did you close the ticket? I offer you an idea to improve the functionality and convenience

**Comment by Darkempire78** [comment]
I closed the ticket because I don't plan to add this feature at the moment. I want to keep a light and efficient application, this feature does not follow the philosophy of OpenCalc

**Comment by OmlineEditor** [comment]
the application should be convenient, not simple. I hope you will make it better in the future.

**Comment by Darkempire78** [comment]
Now that I have enabled discussions on GitHub you can propose your improvement in a post in the discussions to discuss it with other users!

**Comment by OmlineEditor** [comment]
I didn't understand where the discussion is taking place?

**Comment by Darkempire78** [comment]
> I didn't understand where the discussion is taking place?

Here : https://github.com/Darkempire78/OpenCalc/discussions
