### ISSUE TITLE
Buttons are elongated and not spherical for some displays

### ISSUE THREAD

**Issue by adarsh1001** [Darkempire78/OpenCalc#59]
I'm using LG Wing which has a display resolution of 1080x2460. The bubble buttons look pretty elongated in the natural mode which messes up the look of the app. Would be much better looking in my opinion if the buttons were spherical like the example screenshots shown on Github.

![Screenshot_20220910-024243.png](https://user-images.githubusercontent.com/8820038/189447037-20782bf7-3a56-4f17-9519-2555abfdff28.png)

**Comment by adarsh1001** [comment]
I'm not a frontend dev so not familiar with how the UI gets rendered but if I had to guess, we seem to be sizing/stretching the entire UI for whatever resolution we get. Instead, we should render the button pad first with spherical buttons and the rest of the screen height can be taken by the display of the calculator.

**Comment by Darkempire78** [comment]
The size of the buttons changes depending on the height of the phone, they will be flattened on a less tall phone and slightly oval on a very tall phone. i'm not sure to change this 🤔 Perhaps that the best way is to add a max height for the buttons
