### ISSUE TITLE
Relicense opencalc under gpl v2 or apache 2 license

### ISSUE THREAD

**Issue by Umlaut512** [Darkempire78/OpenCalc#60]
Hello I really love your app and use it on my devices. I have a pixel phone which runs grapheneos and it has the stock aosp calculator which not only is ugly as f*** but also receives no updates . I would like to make a proposal to the devs of grapheneos to replace it with your app but because they cannot include strong copyleft licenced code it needs a new license . Preferably apache but gpl v2 will also do .Please take it into consideration and thank you for creating such a beautiful app.

**Comment by Darkempire78** [comment]
I checked these two licenses and I think that I can change for Gpl v2 or Apache v2, that's not a problem

**Comment by Umlaut512** [comment]
Thank you

**Comment by Darkempire78** [comment]
How is it going for GrapheneOS? Will you ask to the dev, or may I should ? To be honest I do not use GraphenOS for the moment (perhaps in the future, seems very interesting). And where to ask ?

**Comment by Umlaut512** [comment]
I have not opened an issue yet i wanted to ask you first if the license change was feasible .I shall do so shortly

**Comment by Umlaut512** [comment]
No luck
https://github.com/GrapheneOS/os-issue-tracker/issues/1469#issuecomment-1242532483

**Comment by Darkempire78** [comment]
In all case, it is planned to improve the calculation system. mxParser is too limited
