### ISSUE TITLE
[Feature Request] Special code will show previously hide apps' list

### ISSUE THREAD

**Issue by serrq** [Darkempire78/OpenCalc#63]
I own several apps that perform functions of utmost importance in the device but would be better was concealed. I mention a few:
Wasted, Sentry, Duress, Photok, etc.

I would like that by entering a special code such as 9999 (the code is user-defined) and long press on = it will show hide apps' list (previously added to OpenCalc).

Of course, OpenCalc should also be able to hide them.

**Comment by Darkempire78** [comment]
this is not the purpose of OpenCalc
