### ISSUE TITLE
Incorrect parentheses handling

### ISSUE THREAD

**Issue by eclairevoyant** [Darkempire78/OpenCalc#65]
The calculator produces a close parenthesis even after operators. For example, if you try to type `2-(3*(4+1))` this calculator shows `2-(3*)4+1((`. However, `3*` is not a valid mathematical expression so the parenthesis should not be closed after this.

**Comment by Darkempire78** [comment]
Fixed 1ff9d9445d9e77f50b60a306ffbbc96643362a12

**Comment by eclairevoyant** [comment]
awesome, thanks!
