### ISSUE TITLE
Everything that I noticed doesn't match with Google's app

### ISSUE THREAD

**Issue by Paol-M** [Darkempire78/OpenCalc#7]
- The delete button isn't filled (is outline only)
- % and ^ are swapped
- π is *endless* on Google's app but not that one
- When there's an error the text doesn't turn red
- Error messages don't say why there's an error
- 0^0 says it's one and not “Undefined or 1” (0^0 = 1 is generally correct see this [Wikipedia article](https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero))
- Typing 50%10 doesn't show what 50% of 10 is. 
- The 3 vertical dots menu doesn't have rounded corners and isn't styled

Obviously they don't have to be identical just wanted to make a helpful list

**Comment by Darkempire78** [comment]
I, OpenCalc does not aim to be Google's calculator, but simply a modern and simpld calculator.

2) I think that ^ id more important than % (perhaps in the future add a setting to custom the button position)
6) I have to check
7) You have to write 50%×10

**Comment by Leif-W** [comment]
I'm no fan of Google at all.  But they do sometimes invest UX development.  So it may be worthwhilevto gain inspiration from basic design elements (UI, theme, transition effects, feedback/errors).  While full feature parity or UI clone is generally undesireable, there may still be ideas to learn from.
