### ISSUE TITLE
Scrolling too fast in the history does funky things

### ISSUE THREAD

**Issue by MKrabs** [Darkempire78/OpenCalc#72]
The scrolling speed afftects the excepted outcome of the scroll-action.

When the initial scroll speed is *high* > the "closing/opening" action is being used.  
When the initial scoll speed is **low** > the "scrolling through the history" action is used.

https://user-images.githubusercontent.com/71791731/200366510-af1cea33-5f53-4a61-be6e-ea7e9e965a88.mp4

(I am not a mobile dev by any means 😅)

Maybe changing the component to a (sun) shade might be more natural. Or something similar to the notification menu:

Swipe down once > open history  
Swipe up (when hitting the bottom of the history) >close the history  
Swipe up (when not at the bottom of the history) > scroll through the history

**Comment by Darkempire78** [comment]
I will remake the history because component used is a little bit glitched

**Comment by Darkempire78** [comment]
It's the same issue that #47
