### ISSUE TITLE
Text overlaps with the dot menu and DEG indicator on very small screen

### ISSUE THREAD

**Issue by MKrabs** [Darkempire78/OpenCalc#73]
The 3 dots menu might be placed inconveniently and feels akward to hit due to it's size.

Having it on the left side might be better, or having a "swipe hamburger menu" could be an alternative.

![Screenshot_20221107_173657_Calculator](https://user-images.githubusercontent.com/71791731/200369666-35fa7e71-a14c-4616-84bd-b1347f675dfb.jpg)

**Comment by Darkempire78** [comment]
I do not really understand the issue, most of three dots are in the right corner of apps

**Comment by MKrabs** [comment]
I mean that the text overlaps with the dot menu. It's easy to hit the menu when you want to select the result.

**Comment by Darkempire78** [comment]
The text should not overlaps with the dot menu. It's a UI issue
