### ISSUE TITLE
Different themes for light and dark mode

### ISSUE THREAD

**Issue by MKrabs** [Darkempire78/OpenCalc#76]
Curently you can only chose from 1 option (between System / AMOLED / etc...).

Choosing individual themes for light and dark modes would be a nice addition.

( + choosing if the theme follows the system or not)

i.e.:

 - [x] Follow OS theme
 - --- Base theme ---
 - [ ] Default
 - [x] Material You
 - [ ] (maybe some predefined colours)
 - --- Dark theme --- (maybe if the option "follow os theme" is not selected, disable these options for visual clarification)
 - [ ] Default
 - [ ] Material You
 - [x] AMOLED
 - [ ] (maybe some predefined colours)

**Comment by Darkempire78** [comment]
I think that currents themes are good
