### ISSUE TITLE
New numbers don't move the older ones

### ISSUE THREAD

**Issue by Gravity2106** [Darkempire78/OpenCalc#79]
On 1.7.3 and 1.8 if you are writing a big calculation you won't see the numbers that go beyond the screen size. 
The screen only shows the first ones until they fill the screen size. If you write more, it makes the calculations, but you cannot see what you are writing

**Comment by Darkempire78** [comment]
That's weird, can you show me a screenshot or a video of the issue ? I'm not able to reproduce it.
What is your device ?

**Comment by Darkempire78** [comment]
Ok, the issue appears only if you never active/move/click the cursor
