### ISSUE TITLE
Calculation history

### ISSUE THREAD

**Issue by shadybraden** [Darkempire78/OpenCalc#8]
Having a calculation history would be amazing.

**Comment by ivan-volnov** [comment]
Great app. Thanks! +1 for the history request

**Comment by Leif-W** [comment]
Also +1 for history.  It was my very second thought, after checking for handling of fractional exponents.

**Comment by Darkempire78** [comment]
Help in adding a draggable panel for the history would be appreciated

**Comment by Darkempire78** [comment]
It will be added in the next update

**Comment by Darkempire78** [comment]
Done 9ca2afc8cf13ce650188f92ca9674549e2df4b8e +

**Comment by julianfairfax** [comment]
Imo this should only persist across a single session. I'm not 100% how Google's does it, but it seems useless to keep history forever.

**Comment by garret** [comment]
@julianfairfax Why? I would actually like that it can last forever or at least having an option to clear the history.

**Comment by ivan-volnov** [comment]
I agree with @garret. It should last forever. Very useful feature is to find out what I calculated last month when I need it.

@Darkempire78 Thank you very much! Haven't tried it yet. Waiting for F-Droid update.
