### ISSUE TITLE
Can't copy results

### ISSUE THREAD

**Issue by Braeise** [Darkempire78/OpenCalc#81]
It doesn't allow [results](https://imgur.com/7q7s90K) to be copied, from the main window or the history. Long pressing on a set of number/s from the history puts the entire formula on the main window instead of just highlighting what you are tapping in order for you to select and copy, paste...etc.

**Comment by Darkempire78** [comment]
Done c7bfb6fe8c0a2db16fc31fefa413b5aa2973d53e & c7bfb6fe8c0a2db16fc31fefa413b5aa2973d53e
