### ISSUE TITLE
History results have no timestamps

### ISSUE THREAD

**Issue by Braeise** [Darkempire78/OpenCalc#82]
I tapped = on Nov 8, 2022 @ 10:00:21. Then later I made another calculation and yaooed = on Nov 9, 2022 @ 08:04:01. Both are recorded history, but no idea when I made them (tapped =).

**Comment by lefterisgar** [comment]
Hi there! Could you please try the attached apk and let me know if anything can be improved? Thanks!
[app-debug.zip](https://github.com/Darkempire78/OpenCalc/files/10719253/app-debug.zip)
