### ISSUE TITLE
Numbers are cutoff in landscape mode 

### ISSUE THREAD

**Issue by user8446** [Darkempire78/OpenCalc#88]
Hi,

After the fix for the larger font size: https://github.com/Darkempire78/OpenCalc/issues/70 (thank you for that!) , the total line numbers are slightly cutoff:

![Screenshot_20221114-094448](https://user-images.githubusercontent.com/18019245/201700144-f4d737e1-abfc-42d0-b985-090675a8c557.jpg)

Also, this is minor and it does not bother me at all but as you can see the numbers are not centered on the keypad buttons.

**Comment by Darkempire78** [comment]
What is the size of your screen ?
