### ISSUE TITLE
Unable to launch app

### ISSUE THREAD

**Issue by KelvinCrag** [Darkempire78/OpenCalc#9]
App keeps force stopping and refuses to open.

![Screenshot_20220729-150945~2](https://user-images.githubusercontent.com/64832927/181778384-547b3c40-9377-43f7-b77f-f207e345897b.png)

Device: Nokia 6.1 Plus, stock rom.
Android version: 10

**Comment by Darkempire78** [comment]
@KelvinCrag Can you try the v1.2.2 please to check if it is fixed ?

**Comment by KelvinCrag** [comment]
Yes 👍
