### ISSUE TITLE
Can't paste a number when the number field is empty

### ISSUE THREAD

**Issue by Tvirin** [Darkempire78/OpenCalc#99]
Can't paste a number when the number field is empty

**Comment by Beersteddy** [comment]
Exactly same problem here.

Strangely this is very common in many android apps

**Comment by Darkempire78** [comment]
the problem is there, but I haven't found a way to solve it yet. If you know how to solve it, don't hesitate

**Comment by Tvirin** [comment]
Maybe you can see how yetCalc from Yet-Zio solved it, project is also written in Kotlin
